### ISSUE TITLE
Cannot start manual migration

### ISSUE THREAD

**Issue by AntonTsaberyaby** [metabase/metabase#10031]
I start the migration from H2 to Postgres by disabling Automigration. But despite the fact that he declared the variable
    - MB_DB_AUTOMIGRATE = false

I do not get the script for manual migration
Part of my docker-compose file

```
version: '2'
services:
  web:
    image: metabase/metabase:v0.32.8
    ports:
      - "3000:3000"
    volumes:
      - ./metabase.db/metabase.db/:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_password
      - MB_DB_AUTOMIGRATE=false
      - MB_DB_HOST=db
      - JAVA_TOOL_OPTIONS=-Xmx3g

    entrypoint: java -jar /app/metabase.jar load-from-h2 /metabase-data/metabase.db

```

Can you help to fix the issue? 

Thanks

```
operating system: Linux
databases: Postgres
Metabase version: (e.x. 0.19.3)
Metabase hosting environment: Docker
Metabase internal database: H2
```
