### ISSUE TITLE
User can't logout / gets automatically logged in.

### ISSUE THREAD

**Issue by mattarderne** [metabase/metabase#10039]
### Bugs

- Your browser and the version: Firefox 66.0.5 (64-bit)
- Your operating system: Mojave
- Your databases: Snowflake
- Metabase version: v0.32.8
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

1. Login to metabase on Firefox 
2. Logout

Expected outcome:
User stays logged out

Actual outcome:
User is logged back in.

Similar experience on Safari, where user is not logged back in unless password is remembered.

Nginx `default.conf` file
```
server {
    listen 80;
    server_name REDACTED;
    return 301 https://REDACTED$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name REDACTED;
    charset utf-8;

    ssl on;
    ssl_certificate /etc/REDACTED;
    ssl_certificate_key /etc/REDACTED;

    location / {
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;

        proxy_pass http://REDACTED:3000;
    }
}
```
`docker-compose.yml`
```
version: "3.5"

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${RDS_CLIENT_ID}
      - MB_DB_PASS=${RDS_CLIENT_PWD}
      - MB_DB_HOST=REDACTED  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - metabase
```

`Dockerfile`
```
FROM tutum/nginx
RUN rm /etc/nginx/sites-enabled/default
ADD default.conf /etc/nginx/sites-enabled/default
WORKDIR /etc/nginx/certs
COPY ./certs /etc/nginx/certs/
```
