### ISSUE TITLE
Metabase behind Traefik fails to load assets

### ISSUE THREAD

**Issue by pierot** [metabase/metabase#10353]
**Describe the bug**
I have set up Metabase behind Traefik, running as a Docker container.
It runs as expected, with SSL, but fails to load logging `net::ERR_CONTENT_DECODING_FAILED 200` errors in the console (Chrome).

Example: https://metabase-cream.jackjoe.be/

**Logs**
Fails to load:
- https://metabase-cream.jackjoe.be/app/dist/vendor.bundle.js?0d1325582067a4b57db2
- https://metabase-cream.jackjoe.be/app/dist/app-main.bundle.js?0d1325582067a4b57db2

```
GET https://metabase-cream.jackjoe.be/app/dist/app-main.bundle.js?0d1325582067a4b57db2 net::ERR_CONTENT_DECODING_FAILED 200

styles.bundle.js?0d1325582067a4b57db2:1 Uncaught ReferenceError: webpackJsonp is not defined at styles.bundle.js?0d1325582067a4b57db2:1
```

**To Reproduce**
Visit: https://metabase-cream.jackjoe.be/

**Expected behavior**
Fully operational Metabase instance.

**Information about your Metabase Installation:**
- Metabase version: (e.x. 0.32.9)
- Metabase hosting environment: Traefik, Docker

**Comment by beyerz** [comment]
I am running Metabase on docker container with Traefik on a separate container and everything works perfectly.

It looks as if your response headers are being duplicated in the request confusing the browser and may lead to the response given in the console. `net::ERR_CONTENT_DECODING_FAILED`.
This is from the request:
https://metabase-cream.jackjoe.be/app/dist/app-main.bundle.js?0d1325582067a4b57db2

I think all the issues are as a result of this.

It is most likely something that you have in your Traefik setup.
Maybe you could include some more information?

**Comment by pierot** [comment]
Docker compose file for Metabase:

```yml
version: '3'

networks:
  web:
    external:
      name: traefik_web

services:
  metabase:
    image: metabase/metabase:v0.32.9
    restart: always
    labels:
      - "traefik.docker.network=traefik_web"
      - "traefik.enable=true"
      - "traefik.backend=metabase"
      - "traefik.frontend.rule=Host:metabase-cream.jackjoe.be"
      - "traefik.port=3000"
    networks:
      - web
    volumes:
      - "/app/metabase-cream.jackjoe.be:/metabase-data"
    environment:
      - "MB_DB_FILE=/metabase-data/metabase.db"
      - "JAVA_TIMEZONE=Europe/Brussels"
      - "MB_ENCRYPTION_SECRET_KEY='XXX'"
```

Docker compose for Traefik:

```yml
version: '3'

networks:
  web:
    driver: bridge

services:
  traefik:
    image: traefik:1.7.12
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./traefik.log:/traefik.log
    container_name: traefik
    networks:
      - web
```

Traefik config:

```toml
debug = false                                                                                                                                                                                                                                                                                                                                                    
defaultEntryPoints = ["http", "https"]                                                                                                                                                    
logLevel = "INFO" 

[traefikLog]
  filePath = "/traefik.log"

[api]
  entrypoint = "dashboard"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true

  [entryPoints.https]
    address = ":443"
    compress = true

    [entryPoints.https.tls]

[acme]
  email = "xxx@xxx.be"
  storage = "/acme.json"
  onHostRule = true
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  entryPoint = "https"

  [acme.httpChallenge]
    entryPoint = "http"

# Hosts
[[acme.domains]]
  main = "metabase-cream.jackjoe.be"
  sans = []

[retry]
  attempts = 10

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
```
