### ISSUE TITLE
Migration documentation seems incorrect about source DB file

### ISSUE THREAD

**Issue by larochew** [metabase/metabase#12100]
**Describe the bug**
I needed to migrate the file-based H2 database to our PostgreSQL setup. We're running metabase inside a docker-compose file. While following the migration documentation (this page https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html), I had issues running the `load-from-h2` command. After tinkering, it seems that the DB file path needs to be set using the env variable and not as an argument to load-from-h2.

Here is the docker-compose file that fails. The database file is located in /metabase-data/metabase.db and is mounted using a docker volume:

```yaml
version: "3.7"
services:
    metabase:
        image: metabase/metabase:latest
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=metabase
            - MB_DB_PASS=postgres
            - MB_DB_HOST=postgres
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "8082:3000"
        command: ["load-from-h2", "/metabase-data/metabase.db"]

    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=metabase
            - POSTGRES_DB=metabase
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    metabase-data:
    pg-data:

```

**Logs**

The above docker-compose file produces the following output:

```
tackv@domcaron:~/stack/backups$ docker-compose up metabase postgres
Starting stack_postgres_1   ... done
Recreating stack_metabase_1 ... done
Attaching to stack_postgres_1, stack_metabase_1
postgres_1    | 
postgres_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1    | 
postgres_1    | 2020-03-11 12:56:43.675 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1    | 2020-03-11 12:56:43.675 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2020-03-11 12:56:43.675 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2020-03-11 12:56:43.692 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2020-03-11 12:56:43.758 UTC [27] LOG:  database system was shut down at 2020-03-11 12:56:40 UTC
postgres_1    | 2020-03-11 12:56:43.779 UTC [1] LOG:  database system is ready to accept connections
metabase_1    | 03-11 12:56:47 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@6e041285
metabase_1    | 03-11 12:56:47 INFO metabase.util :: Loading Metabase...
metabase_1    | 03-11 12:56:47 INFO metabase.util :: Maximum memory available to JVM: 988.0 MB
metabase_1    | 03-11 12:56:58 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
metabase_1    |  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
metabase_1    | 03-11 12:57:04 INFO metabase.db :: Verifying postgres Database Connection ...
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Registered abstract driver :sql  🚚
metabase_1    | Load driver :sql took 87.0 ms
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
metabase_1    | Load driver :sql-jdbc took 109.5 ms
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
metabase_1    | Load driver :postgres took 212.1 ms
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Initializing driver :sql...
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Initializing driver :sql-jdbc...
metabase_1    | 03-11 12:57:04 INFO driver.impl :: Initializing driver :postgres...
metabase_1    | 03-11 12:57:04 INFO metabase.db :: Successfully verified PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) application database connection. ✅
metabase_1    | 03-11 12:57:04 INFO metabase.db :: Running Database Migrations...
metabase_1    | 03-11 12:57:04 INFO metabase.db :: Setting up Liquibase...
metabase_1    | 03-11 12:57:04 INFO metabase.db :: Liquibase is ready.
metabase_1    | 03-11 12:57:04 INFO db.liquibase :: Checking if Database has unrun migrations...
metabase_1    | 03-11 12:57:06 INFO metabase.db :: Database Migrations Current ...  ✅
metabase_1    | Database setup took 1.9 s
metabase_1    | Testing if target DB is already populated...
metabase_1    | [OK]
metabase_1    | Temporarily disabling DB constraints...
metabase_1    | [OK]
metabase_1    | org.h2.jdbc.JdbcSQLException: Database "/metabase.db/metabase.db" not found [90013-197]
metabase_1    |         at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
metabase_1    |         at org.h2.message.DbException.get(DbException.java:179)
metabase_1    |         at org.h2.message.DbException.get(DbException.java:155)
metabase_1    |         at org.h2.engine.Engine.openSession(Engine.java:64)
metabase_1    |         at org.h2.engine.Engine.openSession(Engine.java:179)
metabase_1    |         at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
metabase_1    |         at org.h2.engine.Engine.createSession(Engine.java:140)
metabase_1    |         at org.h2.engine.Engine.createSession(Engine.java:28)
metabase_1    |         at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
metabase_1    |         at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
metabase_1    |         at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
metabase_1    |         at org.h2.Driver.connect(Driver.java:69)
metabase_1    |         at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
metabase_1    |         at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
metabase_1    |         at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
metabase_1    |         at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
metabase_1    |         at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
metabase_1    |         at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
metabase_1    |         at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:161)
metabase_1    |         at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:160)
metabase_1    |         at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__67464.invoke(load_from_h2.clj:257)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
metabase_1    |         at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
metabase_1    |         at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:245)
metabase_1    |         at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:234)
metabase_1    |         at clojure.lang.Var.invoke(Var.java:384)
metabase_1    |         at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
metabase_1    |         at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
metabase_1    |         at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:33)
metabase_1    |         at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
metabase_1    |         at clojure.lang.AFn.applyToHelper(AFn.java:152)
metabase_1    |         at clojure.lang.AFn.applyTo(AFn.java:144)
metabase_1    |         at clojure.core$apply.invokeStatic(core.clj:665)
metabase_1    |         at clojure.core$apply.invoke(core.clj:660)
metabase_1    |         at metabase.cmd$run_cmd$fn__66719.invoke(cmd.clj:127)
metabase_1    |         at metabase.cmd$run_cmd.invokeStatic(cmd.clj:127)
metabase_1    |         at metabase.cmd$run_cmd.invoke(cmd.clj:123)
metabase_1    |         at clojure.lang.Var.invoke(Var.java:388)
metabase_1    |         at metabase.core$run_cmd.invokeStatic(core.clj:132)
metabase_1    |         at metabase.core$run_cmd.invoke(core.clj:130)
metabase_1    |         at metabase.core$_main.invokeStatic(core.clj:141)
metabase_1    |         at metabase.core$_main.doInvoke(core.clj:137)
metabase_1    |         at clojure.lang.RestFn.applyTo(RestFn.java:137)
metabase_1    |         at metabase.core.main(Unknown Source)
metabase_1    | Command failed with exception: Database "/metabase.db/metabase.db" not found [90013-197]
stack_metabase_1 exited with code 1

```

**To Reproduce**

1. Pre-Migration Setup
The first setup of Metabase using the file database can be brought up using the following docker-compose file:

```yaml
version: "3.7"
services:
    metabase:
        image: metabase/metabase:latest
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "8082:3000"
        restart: always

volumes:
    metabase-data:
```

2. Add data to metabase instance for migration (i.e. setup wizard)
3. Swap the docker-compose file for the above one.
4. The above fail output will be generated.

To fix the issue, the following docker-compose file was used. Changes:
- Specify `MB_DB_FILE` instead of the load-from-h2 argument.

```yaml
version: "3.7"
services:
    metabase:
        image: metabase/metabase:latest
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=metabase
            - MB_DB_PASS=postgres
            - MB_DB_HOST=postgres
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "8082:3000"
        command: ["load-from-h2"]
        restart: always

    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=metabase
            - POSTGRES_DB=metabase
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    mongodb-data:
    metabase-data:
```

Output becomes:
```
tackv@domcaron:~/stack/backups$ docker-compose up metabase postgres
Starting stack_postgres_1   ... done
Recreating stack_metabase_1 ... done
Attaching to stack_postgres_1, stack_metabase_1
postgres_1    | 
postgres_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1    | 
postgres_1    | 2020-03-11 12:57:39.371 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1    | 2020-03-11 12:57:39.371 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2020-03-11 12:57:39.371 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2020-03-11 12:57:39.388 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2020-03-11 12:57:39.424 UTC [26] LOG:  database system was shut down at 2020-03-11 12:57:23 UTC
postgres_1    | 2020-03-11 12:57:39.443 UTC [1] LOG:  database system is ready to accept connections
metabase_1    | 03-11 12:57:42 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@52f57666
metabase_1    | 03-11 12:57:42 INFO metabase.util :: Loading Metabase...
metabase_1    | 03-11 12:57:42 INFO metabase.util :: Maximum memory available to JVM: 988.0 MB
metabase_1    | 03-11 12:57:54 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
metabase_1    |  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
metabase_1    | 03-11 12:58:00 INFO metabase.db :: Verifying postgres Database Connection ...
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Registered abstract driver :sql  🚚
metabase_1    | Load driver :sql took 91.9 ms
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
metabase_1    | Load driver :sql-jdbc took 110.2 ms
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
metabase_1    | Load driver :postgres took 218.3 ms
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Initializing driver :sql...
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Initializing driver :sql-jdbc...
metabase_1    | 03-11 12:58:00 INFO driver.impl :: Initializing driver :postgres...
metabase_1    | 03-11 12:58:00 INFO metabase.db :: Successfully verified PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) application database connection. ✅
metabase_1    | 03-11 12:58:00 INFO metabase.db :: Running Database Migrations...
metabase_1    | 03-11 12:58:00 INFO metabase.db :: Setting up Liquibase...
metabase_1    | 03-11 12:58:00 INFO metabase.db :: Liquibase is ready.
metabase_1    | 03-11 12:58:00 INFO db.liquibase :: Checking if Database has unrun migrations...
metabase_1    | 03-11 12:58:02 INFO metabase.db :: Database Migrations Current ...  ✅
metabase_1    | Database setup took 2.5 s
metabase_1    | Testing if target DB is already populated...
metabase_1    | [OK]
metabase_1    | Temporarily disabling DB constraints...
metabase_1    | [OK]
metabase_1    | Transfering 2 instances of Database....[OK]
metabase_1    | Transfering 1 instances of User....[OK]
metabase_1    | Transfering 11 instances of Setting....[OK]
metabase_1    | Transfering 71 instances of Dependency....[OK]
metabase_1    | Transfering 5 instances of Table....[OK]
metabase_1    | Transfering 83 instances of Field....[OK]
metabase_1    | Transfering 37 instances of FieldValues....[OK]
metabase_1    | Transfering 2 instances of Segment....[OK]
metabase_1    | Transfering 7 instances of Metric....[OK]
metabase_1    | Transfering 153 instances of Revision.....[OK]
metabase_1    | Transfering 438 instances of ViewLog........[OK]
metabase_1    | Transfering 3 instances of Session....[OK]
metabase_1    | Transfering 4 instances of Dashboard....[OK]
metabase_1    | Transfering 46 instances of Card....[OK]
metabase_1    | Transfering 31 instances of DashboardCard....[OK]
metabase_1    | Transfering 2 instances of DashboardCardSeries....[OK]
metabase_1    | Transfering 163 instances of Activity.....[OK]
metabase_1    | Transfering 3 instances of PermissionsGroup....[OK]
metabase_1    | Transfering 2 instances of PermissionsGroupMembership....[OK]
metabase_1    | Transfering 5 instances of Permissions....[OK]
metabase_1    | Transfering 1 instances of Collection....[OK]
metabase_1    | Transfering 14 instances of DataMigrations....[OK]
metabase_1    | Re-enabling DB constraints...
metabase_1    | [OK]
metabase_1    | Setting postgres sequence ids to proper values...
metabase_1    | [OK]
stack_metabase_1 exited with code 0

```

After removing the command key from the metabase service, the metabase instance seems migrated to PostgreSQL.

**Severity**
Low, probably a simple documentation update since the migration works.
