### ISSUE TITLE
Can't turn off HTTPS redirect

### ISSUE THREAD

**Issue by amir5121** [metabase/metabase#13084]
**Describe the bug**
Can't turn off HTTPS redirect since metabase not respecting environment variables. I accidentally enabled always redirect on from admin panel and now i can't turn it off since metabase doesn't have a valid SSL and it is always redirecting to HTTPS. 
[here](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html) mentions 

> The environment variables always take precedence.

But after setting the environment variable i am still being redirected to HTTPS and i'm stuck. 

here are my ENVs
```
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=****
TERM=xterm
JAVA_TOOL_OPTIONS=-Xmx4096m
MB_DB_FILE=/metabase-data/metabase.db
MB_REDIRECT_ALL_REQUESTS_TO_HTTPS=false
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk-11.0.8+10
JAVA_HOME=/opt/java/openjdk
FC_LANG=en-US
LC_CTYPE=en_US.UTF-8
HOME=/root

```
**Logs** 
`2020/08/07 21:18:39 [error] 11963#11963: *6024 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: ****, server: metabase.example.com, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:3000/", host: "metabase.example.com"`

**To Reproduce**
1. Enable HTTPS redirect from admin panel when you don't have a certificate setup
2. set MB_REDIRECT_ALL_REQUESTS_TO_HTTPS to false

**Expected behavior**
disabling HTTPS redirect

**Information about your Metabase Installation:**

- Metabase version: (e.x. 0.36.3)
- Metabase hosting environment: (Docker stack)

**Severity**
Well it's on production server and no one can access metabase 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by amir5121** [comment]
This issue still persist and i would happily do a PR if someone guide me thought how metabase is supposed to treat Environment variables.

i resolved my own issue( caused by my own stupidity) by editing Metabase database itself.. though i ended up migrating from H2 to postgres and initiate metabase container with `top` command so the migration lock is lifted so i could do the migration.
Here is my metabase stack config for anyone in the future facing this

`docker-stack.yml`
```
version: '3.7'

services:
  metabase:
    image: metabase/metabase
#    command: ['sh', '-c', 'top']
    networks:
      - bb-db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: password
      MB_DB_HOST: bb-db_postgres
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_TOOL_OPTIONS: -Xmx4096m
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '6'
          memory: 6G
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./metabase-data/:/metabase-data
    ports:
      - "46699:3000"

networks:
  bb-db:
    external:
      name: bb-db                 
```

and to update setting in `psql`:
`update setting set value = false where key = 'redirect-all-requests-to-https';`
