### ISSUE TITLE
Remove useless and unused CSS animations

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#14268]
**Describe the issue**
While working on `DashCard` unit test I discovered that `.Card--active` css class is used to set the 30s long animation to the newly added card. Apart from it being too long, it doesn't have any visual effect:
```css
@keyframes fade-out-yellow {
  from {
    background-color: var(--color-bg-white);
  }
  to {
    background-color: var(--color-bg-white);
  }
}

.Dash--editing .DashCard .Card.Card--recent {
  animation-duration: 30s;
  animation-name: fade-out-yellow;
}
```

**Expected behavior**
The animation should either be faster (and it result in some visual effect) or it should be removed. Since we didn't use any effect for newly added dashboard cards, it should be removed.

_There are a few additional completely unused animations floating around that should be removed as well._

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/103700361-a49e4a00-4fa4-11eb-8e10-318debbb8c31.png)

**Severity**
Not sure to what extent this affects performance but it definitely seems like unnecessary additional load.
