### ISSUE TITLE
Pivot tables don’t look right in dark mode (embedded preview)

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#14326]
**Describe the bug**
Pivot table visualization doesn't look right in dark mode in embedded previews. It seems that there is no CSS dealing with this context.

**Logs**
N/A

**To Reproduce**
1. Create a question with pivot table visualization and save it (adding it to the dashboard or not doesn't make any difference)
2. Click on sharing icon, then choose "Sharing and embedding"
3. Embed this question/dashboard in an application
4. In the right sidebar choose Dark mode
5. Note that cells' background color is hardcoded and doesn't adjust to the dark mode

**Expected behavior**
There should be a style specific to the dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/104051515-8c1e7180-51e8-11eb-95eb-21819d449f60.png)

**Severity**
Functionality doesn't seem to be affected, but it looks weird and it's really hard to read some fields.

**Additional Context**
`frontend/src/metabase/css/core/colors.css`

```css
.bg-light, .bg-light-hover:hover {
    background-color: #f9fbfc;
}

.bg-medium, .bg-medium-hover:hover {
    background-color: #edf2f5;
}

.text-dark {
    color: #4c5773;
}

.text-medium {
    color: #949aab;
}
```

It seems that (at least when it comes to the text color) there was some CSS dealing with the night mode but it's being overwritten here:
![image](https://user-images.githubusercontent.com/31325167/104052262-bb81ae00-51e9-11eb-92b6-7a6186687e6d.png)

Also, note that CSS is included twice - reported in #13219
