### ISSUE TITLE
[Feature Request] Environment variable for additional DB params

### ISSUE THREAD

**Issue by jabbors** [metabase/metabase#14764]
**Is your feature request related to a problem? Please describe.**
When we provision a database (in kubernetes) for storing Metabase metadata, the tool generates a kubernetes secret containing the user account details for connecting to this database. The database will only accept TLS connections and the certificate is self-signed, meaning that we must configure metabase to use SSL and ignore verification.

Although this is possible with the `MB_DB_CONNECTION_URI` environment variable, our automated GitOps deployment would require two steps to setup a Metabase service. First we must declare to setup the database, wait for it to be deployed and the secret generated. Then we can pull the credentials from the secret and defined them in the `MB_DB_CONNECTION_URI`.

**Describe the solution you'd like**
I would like to be able to configure additional DB connection parameters through a separate environment variable, ie. `MB_DB_PARAMS`.

This suggestions introduces a more cloud-native and cloud friendly experience for running Metabase in Kubernetes.

If this feature gets implemented, Metabase can be confined with something like

```
env:
  - name: MB_DB_TYPE
    value: postgres
  - name: MB_DB_DBNAME
    value: metabase
  - name: MB_DB_HOST
    value: metabase.metabase.svc.cluster.local
  - name: MB_DB_PORT
    value: '5432'
  - name: MB_DB_USER
    valueFrom:
      secretKeyRef:
        name: metabase-credentials
        key: username
  - name: MB_DB_PASS
    valueFrom:
      secretKeyRef:
        name: metabase-credentials
        key: password
  - name: MB_DB_PARAMS
    value: ssl=true&sslmode=required
```

Which looks more complex than

```
env:
  - name: MB_DB_CONNECTION_URI
    valueFrom:
      secretKeyRef:
        name: metabase-uri
        key: connection-uri
```

But in the latter case I have to encrypt the entire connection URI (when only the user credentials needs encryption) so it can be put into the git repository and then it must be decrypted when it's applied in kubernetes. If the former case, the configuration block can go into git in plaintext, which is a lot east to maintain.

**How important is this feature to you?**
High/Very. We use k8s to host every service and it's a strong requirement that when the application manifests goes into our git repository for production environments, the service must be able to start up without any manual interaction. This is for ensuring we have a smooth and quick disaster recovery. A relaxation means the disaster recovery plan must be adjusted.
