### ISSUE TITLE
Docker secrets files used as string literals

### ISSUE THREAD

**Issue by dannydnz** [metabase/metabase#16026]
**Describe the bug**
When setting 

````yml
      MB_DB_USER: /run/secrets/db_user
      MB_DB_PASS: /run/secrets/db_password
      MB_DB_DBNAME: /run/secrets/db_name
````

as per the  documentation in a docker compose file, with the appropriate secret configuration, the literal  "/run/secrets/db_name" , "/run/secrets/db_user" and "/run/secrets/db_password" are used as the database name,  user and password.

````cli
metabase_1        | Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=405) Access denied for user '/run/secrets/db_user'@'172.19.0.16' (using password: YES)
metabase_1        | Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
````

Suggested fix would be to follow the postgres and mysql container secrets environment variable conventions.
They append _FILE to the environment variable if it is populated using a secret.
@see https://hub.docker.com/_/Mysql
@see https://hub.docker.com/_/postgres

Example 
````yml
      MB_DB_USER: /run/secrets/db_user
      MB_DB_PASS: /run/secrets/db_password
      MB_DB_DBNAME: /run/secrets/db_name
````

Would become 
````yml
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_DBNAME_FILE: /run/secrets/db_name
````

These changes could be implemented with a small mod to the /bin/docker/run_metabase.sh file.

````bash
# check for docker secrets file
if [[ -n "${MB_DB_USER_FILE}" ]]; then
  export MB_DB_USER=$(cat ${MB_DB_USER_FILE})
  echo "metabase db username set from secrets file ${MB_DB_USER_FILE}"
fi

if [[  -n "${MB_DB_PASS_FILE}" ]]; then
    export MB_DB_PASS=$(cat ${MB_DB_PASS_FILE})
  echo "metabase db password set from secrets file ${MB_DB_PASS_FILE}"
fi

if [[  -n "${MB_DB_DBNAME_FILE}" ]]; then
    export MB_DB_DBNAME=$(cat ${MB_DB_DBNAME_FILE})
  echo "metabase db name set from secrets file ${MB_DB_DBNAME_FILE}"
fi
````

**Comment by shimisnow** [comment]
The pull request #16876 referenced by @flamber is not a solution for this issue.

The pull request is about changing the documentation to reflect the config for Postgres ENV variables. This issue is about a bug that occurs in the Metabase ENV variables where the secret path is not parsed and treated as literal.

**Comment by flamber** [comment]
@shimisnow So you're saying that #7464 was never implemented?
Then it's not a bug, it's a feature request. Metabase requires the MB_DB_USER and MB_DB_PASS to be strings.

**Comment by shimisnow** [comment]
Well, @dannydnz  opened the issue to tell that the values in MB_DB_USER and MB_DB_PASS were being treated as strings, as you also said.

The point is that this page https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html shows that we can use secrets at MB_DB_USER and MB_DB_PASS, buts this simply do not work.

My docker-compose.yml is:

```yml
version: '3.8'

secrets:
  mariadb_root_password:
    external: true
  metabase_database_user:
    external: true
  metabase_database_password:
    external: true

services:	
  database:
    image: mariadb:10.6.4
    secrets:
      - mariadb_root_password
      - metabase_database_user
      - metabase_database_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_USER_FILE: /run/secrets/metabase_database_user
      MARIADB_PASSWORD_FILE: /run/secrets/metabase_database_password
      MARIADB_DATABASE: ${METABASE_DATABASE_NAME}

  metabase:
    image: metabase/metabase:v0.40.3.1
    depends_on: 
      - database
    networks:
      - metabase
    ports:
      - 3000:3000
    secrets:
      - metabase_database_user
      - metabase_database_password
    environment:
      MB_DB_TYPE: mysql
      MB_DB_HOST: database
      MB_DB_PORT: 3306
      MB_DB_USER: /run/secrets/metabase_database_user
      MB_DB_PASS: /run/secrets/metabase_database_password
      MB_DB_DBNAME: ${METABASE_DATABASE_NAME}
      JAVA_TIMEZONE: Europe/London
```

The error is always `Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=database)(port=3306)(type=master) : (conn=19) Access denied for user '/run/secrets/metabase_database_user'@'10.0.14.6' (using password: YES)`

The conclusion is:

1. As you said, the two mentioned variables **need to be string**, so the doc cannot show tha a secret can be used.
2. This issue is a feature request.
3. The doc has an error caused by #14839

**Comment by flamber** [comment]
@shimisnow I don't have time to test around with this, but your secrets are not using `file:` parameter:
https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets-configuration-reference
Something like this should work, where those files have to be in the same dir as your compose.
```
secrets:
  mariadb_root_password:
     file: db_root_password.txt
  metabase_database_user:
     file: db_user.txt
  metabase_database_password:
     file: db_password.txt
```

**Comment by shimisnow** [comment]
Tested with:

```yml
secrets:
  mariadb_root_password:
    file: ./mariadb_root_password.secret
  metabase_database_user:
    file: ./metabase_database_user.secret
  metabase_database_password:
    file: ./metabase_database_password.secret
```
and
```yml
secrets:
  mariadb_root_password:
    external: true
  metabase_database_user:
    external: true
  metabase_database_password:
    external: true
```

In both cases, mariadb environment variables (see previous comment for details) that uses secrets worked, but not the ones from metabase, with the error `Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=3) Access denied for user '/run/secrets/metabase_database_user'@'10.0.19.4' (using password: YES)`

I am confident to say that the metabase image do not supports docker secrets and the examples using it should be removed from the documentation.

**Comment by taurus227** [comment]
@flamber I think there is a misunderstanding.
- From [the docs](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images):
> Docker secrets do not set environment variables directly. This was a conscious decision, because environment variables can unintentionally be leaked between containers (for instance, if you use --link).

- Also from [the docs](https://docs.docker.com/engine/swarm/secrets/#advanced-example-use-secrets-with-a-wordpress-service):
> The secrets are each mounted in a tmpfs filesystem at /run/secrets/... They are never exposed as environment variables, nor can they be committed to an image if the docker commit command is run. 

So the only way to use docker secrets is if the service itself (i.e. metabase) is able to read the credentials from files instead of environment variables. All such services (mysql, postgres, wordpress) use the convention of allowing the user to specify a `PASSWORD_FILE` variable instead of a `PASSWORD` variable, then the service reads the password from that file. This ticket is proposing the equivalent solution to be implemented in Metabase.

**Comment by shimisnow** [comment]
I can confirm that the code provided by @dannydnz works when added to the `/bin/docker/run_metabase.sh` file at line 19.

If someone wants to verify this in a simple way, follow the steps:

1. Download the project files (Dockerfile and run_metabase.sh) from /bin/docker/
2. Add the provided code to `run_metabase.sh` at line **19**
3. Download the jar file from a release (tested with v0.41.1) and put it in the same directory as the Dockerfile
4. Run `docker build -t metabase/metabase:v0.41.1-test .`
5. Start a container using the `-test` image

Example:

```yml
version: '3.8'
services:
  metabase:
    image: metabase/metabase:v0.41.1-test
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: host
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_DBNAME_FILE: /run/secrets/db_name
    secrets:
      - db_password
      - db_user
      - db_name

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
  db_name:
    file: db_name.txt
```
