### ISSUE TITLE
PostgreSQL primary-secondary connection string incorrectly parsed

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#16106]
**Describe the bug**
According to https://jdbc.postgresql.org/documentation/head/connect.html#connection-failover (the driver we use), you could pass a connection string with the following pattern: "postgresql://host1:port1,host2:port2/database" but it will fail in the MB_DB_CONNECTION_URI env var with the error "Caused by: org.postgresql.util.PSQLException: Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."

**Logs**
<details>

```
metabase     | clojure.lang.ExceptionInfo: Unable to connect to Metabase postgres DB. {}
metabase     | 	at metabase.db.setup$fn__35138$verify_db_connection__35143$fn__35144$fn__35145.invoke(setup.clj:102)
metabase     | 	at metabase.db.setup$fn__35138$verify_db_connection__35143$fn__35144.invoke(setup.clj:100)
metabase     | 	at metabase.db.setup$fn__35138$verify_db_connection__35143.invoke(setup.clj:94)
metabase     | 	at metabase.db.setup$setup_db_BANG_$fn__35173$fn__35174.invoke(setup.clj:142)
metabase     | 	at metabase.util$do_with_us_locale.invokeStatic(util.clj:687)
metabase     | 	at metabase.util$do_with_us_locale.invoke(util.clj:673)
metabase     | 	at metabase.db.setup$setup_db_BANG_$fn__35173.invoke(setup.clj:141)
metabase     | 	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
metabase     | 	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
metabase     | 	at metabase.db$setup_db_BANG_$fn__35187.invoke(db.clj:61)
metabase     | 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
metabase     | 	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
metabase     | 	at metabase.core$init_BANG_.invokeStatic(core.clj:95)
metabase     | 	at metabase.core$init_BANG_.invoke(core.clj:74)
metabase     | 	at metabase.core$start_normally.invokeStatic(core.clj:139)
metabase     | 	at metabase.core$start_normally.invoke(core.clj:133)
metabase     | 	at metabase.core$_main.invokeStatic(core.clj:172)
metabase     | 	at metabase.core$_main.doInvoke(core.clj:166)
metabase     | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase     | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
metabase     | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
metabase     | 	at metabase.core.main(Unknown Source)
metabase     | Caused by: org.postgresql.util.PSQLException: Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
metabase     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
metabase     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
metabase     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
metabase     | 	at org.postgresql.Driver.makeConnection(Driver.java:465)
metabase     | 	at org.postgresql.Driver.connect(Driver.java:264)
metabase     | 	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
metabase     | 	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
metabase     | 	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
metabase     | 	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
metabase     | 	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
metabase     | 	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
metabase     | 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
metabase     | 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
metabase     | 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
metabase     | 	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
metabase     | 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
metabase     | 	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
metabase     | 	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:199)
metabase     | 	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:196)
metabase     | 	at metabase.db.setup$fn__35138$verify_db_connection__35143$fn__35144$fn__35145.invoke(setup.clj:100)
metabase     | 	... 21 more
metabase     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
metabase     | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
metabase     | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
metabase     | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
metabase     | 	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
metabase     | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
metabase     | 	at java.base/java.net.Socket.connect(Unknown Source)
metabase     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
metabase     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:95)
metabase     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
metabase     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
metabase     | 	... 40 more
```

</details>

**To Reproduce**
copy and paste the following docker compose file somewhere and "docker-compose up" there (yes, it's not clusterized but it will work)
<details>

```
version: '3.7'
services:
  metabase:
    # image: metabase/metabase-enterprise:v1.38.0
    image: metabase/metabase:v0.39.1
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3031:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_CONNECTION_URI=postgresql://postgres1:5432,postgres2:5432/metabase?user=metabase&password=mysecretpassword"
      # - "MB_DB_DBNAME=metabase"
      # - "MB_DB_PORT=5432"
      # - "MB_DB_USER=metabase"
      # - "MB_DB_PASS=mysecretpassword"
      # - "MB_DB_HOST=postgres"
    networks: 
      - metanet1
    depends_on: 
      - postgres
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    hostname: postgres
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1
  postgres2:
    image: postgres:13.3-alpine
    container_name: postgres2
    hostname: postgres2
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1
```

</details>

**Expected behavior**
Metabase should be able to connect without issues if you set up a "primary-secondary" cluster type with different ports

**Screenshots**
N/A

**Information about your Metabase Installation:**
- Your browser and the version: Brave lates
- Your operating system: Ubuntu Desktop latest LTS
- Your databases: H2
- Metabase version: 0.39.1
- Metabase hosting environment: Docker
- Metabase internal database: Trying a postgres primary-secondary!

**Severity**
Minor

**Additional context**
Reported by a customer

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment
