### ISSUE TITLE
Serialization: Visualization column settings lost

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#16150]
**Describe the bug**
The `report_card.visualization_settings` are not getting references during `dump` for "column_settings", and "table.columns" are not being translated during `load`, so all customizations are lost during Serialization.
The same thing applies to `report_dashboardcard.visualization_settings`.

**To Reproduce**
1. On source: Simple question > Sample Dataset > Orders
2. Click visualization Settings and do the following -  and then save the question
   1. change the title of ID column
   2. hide EAN column
   3. add "Show a mini bar chart" on Rating column
3. Serialization dump - the card yaml is correctly saving "table.columns" references, but "column_settings" are not translated:
```yaml
...
visualization_settings:
  table.columns:
  - name: ID
    fieldRef:
    - field
    - /databases/Sample Dataset/schemas/PUBLIC/tables/PRODUCTS/fields/ID
    - null
    enabled: true
  - name: EAN
    fieldRef:
    - field
    - /databases/Sample Dataset/schemas/PUBLIC/tables/PRODUCTS/fields/EAN
    - null
    enabled: false
...
  column_settings:
    '["ref",["field",8,null]]':
      column_title: 'MOD: ID'
    '["ref",["field",6,null]]':
      show_mini_bar: true
      column_title: 'MOD: Rating'
...
```
4. Serialization load - the `report_card.visualization_settings` on the target will not have translated references:
```
...{"table.columns":[{"name":"ID","fieldRef":["field","/databases/Sample Dataset/schemas/PUBLIC/tables/PRODUCTS/fields/ID",null],"enabled":true},{"name":"EAN","fieldRef":["field","/databases/Sample Dataset/schemas/PUBLIC/tables/PRODUCTS/fields/EAN",null],"enabled":false},...
```
And "column_settings" is referencing fields on the source - not the target - and show_mini_bar attribute is dropped too:
```json
  "column_settings": {
    "[\"ref\",[\"field\",8,null]]": {
      "column_title": "MOD: ID"
    },
    "[\"ref\",[\"field\",6,null]]": {
      "": true,
      "column_title": "MOD: Rating"
    }
  }
```

This means that any column modifications are lost.
If this target instance is used as source in a new Serialization, then the dump process can completely break (like if database/table/column has gotten a new name), because it seems to do a lookup on "table.columns" references on dump (huh?)

**Information about your Metabase Installation:**
Tested 1.38.1 thru 1.39.2 and `serialization-fixes` commit `bffb807`

**Additional context**
Related to #11829

----

<details><summary>Possible workaround for Postgres to cleanup "table.columns" on target - it will *not* fix "column_settings"</summary>

```sql
-- IMPORTANT: This query does not handle encoded characters.
-- So if database/schema/table/column contains special characters (eg. %2F), then something like this is needed too: https://stackoverflow.com/questions/6410088/how-can-i-mimic-the-php-urldecode-function-in-postgresql

-- IMPORTANT: Make a backup before running this query! The query is only written for Postgres.
-- It's recommended to run the query between the "checker" comments to see which cards might be modified.

-- IMPORTANT: The update query has to be run multiple times until there are no more updated rows.
-- This is a limitation of Postgres' "UPDATE ... FROM": https://www.postgresql.org/docs/current/sql-update.html#id-1.9.3.182.8

UPDATE report_card
SET visualization_settings=REGEXP_REPLACE(visualization_settings, lookup.findstr, lookup.replacestr)
FROM (
    -- checker:begin
    WITH wrongref AS (
        SELECT rc.id, REGEXP_MATCH(rc.visualization_settings, '"field",("/databases/([^/]+)/schemas/([^/]+)/tables/([^/]+)/(fields|fks)/([^"]+)")') AS findstr
        FROM report_card AS rc WHERE rc.visualization_settings LIKE '%"field","/databases/%'
    )
    SELECT
      wrongref.id,
      concat('"field",', wrongref.findstr[1]) AS findstr,
      concat('"field",', (
        SELECT mf.id::varchar
        FROM metabase_database AS md
        LEFT JOIN metabase_table AS mt ON mt.db_id=md.id
        LEFT JOIN metabase_field AS mf ON mf.table_id=mt.id
        WHERE md."name"=wrongref.findstr[2] AND mt."schema"=wrongref.findstr[3] AND mt."name"=wrongref.findstr[4] AND mf."name"=wrongref.findstr[6])
      ) AS replacestr
    FROM wrongref
    -- checker:end
) AS lookup
WHERE report_card.id=lookup.id
AND lookup.replacestr <> '"field",' -- make sure it doesn't replace unknown references (eg. special characters or renamed objects)
```

</details>
