### ISSUE TITLE
Metabase on Docker with network host mode

### ISSUE THREAD

**Issue by mcardia** [metabase/metabase#16206]
**Describe the bug**
Hi!

If I run the metabase docker image in bridge mode + port biding, it works. But I need to make it run
in "host" mode. When my compose is up, it connects to mysql, but I can't connect to the http 3000 port.

I tried to use MB_JETTY_HOST=0.0.0.0, but in the image, metabase is listening only the IPv6 :::3000, not the IPv4.

Can anyone help me?
Thank you
**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
```
version: "3.9"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: *****
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
```

```docker-compose -f mysql.yml up```

```
version: "3.9"
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: unless-stopped
    network_mode: host
    environment:
    - JAVA_TIMEZONE=America/Sao_Paulo
    - MB_JETTY_HOST=0.0.0.0
    - MB_DB_TYPE=mysql
    - MB_DB_DBNAME=metabase
    - MB_DB_PORT=3306
    - MB_DB_USER=metabase
    - MB_DB_PASS=******
    - MB_DB_HOST=localhost
```

```docker-compose -f metabase.yml up```

**Expected behavior**
Access http://127.0.0.1:3000/setup/

**Severity**
this is annoying
