### ISSUE TITLE
Webpack building hot-reload builds with Dockerfile

### ISSUE THREAD

**Issue by ChakshuGautam** [metabase/metabase#17632]
**Describe the bug**
Webpack building `NODE_ENV=hot` builds with Dockerfile. Even though the NODE_ENV is set to `production` in the Dockerfile. The use case was to create an end-to-end feature add to metabase.

**Logs**
![Screenshot 2021-08-27 at 1 45 02 PM](https://user-images.githubusercontent.com/7413816/131096333-7deac652-b5c0-438e-b61c-7357d305e045.png)

**Steps To Reproduce**
1.  Forked the repo [here](https://github.com/Samagra-Development/metabase)
2. Made some changes (Can be seen pushed to [feature/map](https://github.com/Samagra-Development/metabase/tree/feature/map))
3. `docker build -t bla/metabase .`
4. Setup nginx proxy and deploy using the following docker-compose.yml
```yml
version: "3"
services:
  metabase:
    image: samagrgovernance/metabase
    environment:
      - MB_SITE_URL=http://dev-metabase.samagra.io
      - JAVA_OPTS=-Xmx6g
    volumes:
      - ./metabase-app:/data
    ports:
      - "5003:3000"
```

```nginx
server {
        server_name dev-metabase.samagra.io;

        location / {
                proxy_pass http://localhost:5003/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-Proto https;
                proxy_hide_header X-Frame-Options;
                add_header X-Frame-Options "ALLOWALL";
                proxy_hide_header Content-Security-Policy;
        }
}
```

**Expected behavior**
Webpack should use `dev-metabase.samagra.io` as the base URL rather than `localhost:8080` which is part of the dev server.

Metabase is deployed here and can be used for debugging - http://dev-metabase.samagra.io/
