### ISSUE TITLE
Serialization: Models metadata not included in `dump`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20282]
**Describe the bug**
Models metadata not included in Serialization `dump`

**To Reproduce**
1. On source, create a SQL question (e.g. Products) and convert to Model and assign all the metadata to the real fields
2. Serialization `dump` - looking at the yaml-file, it does not include any metadata information
```yaml
enable_embedding: false
visualization_settings:
  table.pivot_column: CATEGORY
  table.cell_column: ID
dataset: true
dataset_query:
  type: native
  native:
    query: SELECT * FROM "PRODUCTS"
    template-tags: {}
  database: /databases/Sample Database
name: Dataset - SQL products
archived: false
collection_position: null
database_id: /databases/Sample Database
embedding_params: null
table_id: null
query_type: native
cache_ttl: null
display: table
public_uuid: null
description: null
```

**Information about your Metabase Installation:**
1.42.0-rc2
