### ISSUE TITLE
Split up legacy Liquibase migrations with multiple `changeSet`s 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20995]
Some of our older Liquibase `changeSet`s have multiple changes each. That's generally a bad idea because MySQL can't do DDL statements inside transactions, which means `changeSet`s with multiple `changes` aren't atomic. It's possible for example for a `changeSet` with two `createTable` changes to start running, do the first change successfully, then fail on the second; the entire `changeSet` fails, and trying to re-run it will result in trying to do both changes again; the first one will almost certainly fail because that table already exists.

I think we should take those older migrations and split them up into migrations with one change each. Example:

https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L4027-L4046

```yaml
  - changeSet:
      id: 68
      author: sbelak
      comment: 'Added 0.27.0'
      validCheckSum:
        - 8:ca201aeb20c1719a46c6bcc3fc95c81d
        - 8:b4ac06d133dfbdc6567d992c7e18c6ec
      changes:
        - addColumn:
            tableName: computation_job
            columns:
              - column:
                  name: context
                  type: text
        - addColumn:
            tableName: computation_job
            columns:
              - column:
                  name: ended_at
                  type: DATETIME
```

Could be rewritten as:

```yaml
  - changeSet:
      id: 68a
      author: sbelak
      comment: 'Added 0.27.0'
      preConditions:
        - onFail: MARK_RAN
        - or:
            - and:
                - dbms:
                    type: postgresql,h2
                - sqlCheck:
                    expectedResult: 0
                    sql: SELECT count(*) FROM databasechangelog WHERE id = '68';
            - and:
                - dbms:
                    type: mysql,mariadb
                - sqlCheck:
                    expectedResult: 0
                    sql: SELECT count(*) FROM `DATABASECHANGELOG` WHERE id = '68';
              
      changes:
        - addColumn:
            tableName: computation_job
            columns:
              - column:
                  name: context
                  type: text

  - changeSet:
      id: 68b
      author: sbelak
      comment: 'Added 0.27.0'
      preConditions:
        - onFail: MARK_RAN
        - or:
            - and:
                - dbms:
                    type: postgresql,h2
                - sqlCheck:
                    expectedResult: 0
                    sql: SELECT count(*) FROM databasechangelog WHERE id = '68';
            - and:
                - dbms:
                    type: mysql,mariadb
                - sqlCheck:
                    expectedResult: 0
                    sql: SELECT count(*) FROM `DATABASECHANGELOG` WHERE id = '68';
              
      changes:
        - addColumn:
            tableName: computation_job
            columns:
              - column:
                  name: context
                  type: text
```

That's obviously pretty verbose. Maybe we can create a custom `preCondition` type so we don't have to repeat that stuff over and over .

Either way, this would make our migrations a lot more robust and mean people wouldn't have to manually much around with their application DB if something failed partway thru
