### ISSUE TITLE
Serialization: order of keys is not consistent

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#22196]
**Is your feature request related to a problem? Please describe.**
The order of keys in a serialized yaml is not consistent. When comparing two different yamls for the exact same instance, a comparison tool like git can find differences when there is none.

**Describe the solution you'd like**
The order of the keys should be consistent.
The order of nested elements should also be consistent.

**How important is this feature to you?**
It is a requirement for the git integration story.

**Comment by luizarakaki** [comment]
Closed with #25021

**Comment by bshepherdson** [comment]
This issue is back! Somewhere through the refactorings of serdes, this regressed and nothing was testing it. It's important to enable git diffs etc. that the serdes output be consistent.

- Within each entity the keys must be ordered.
- Any embedded lists (eg. dashcards) should be `select`ed in any consistent, portable order. (`entity_id` is an obvious one; `id` doesn't work since they may not match.)

**Comment by darksciencebase** [comment]
probably fixed by https://github.com/metabase/metabase/pull/34818, but we need tests

**Comment by piranha** [comment]
Seems like it's not fixed in #34818, as `.yaml` files I'm seeing are like this:

```yaml
description: null
archived: false
collection_position: null
table_id: null
result_metadata: null
database_id: test-data
enable_embedding: false
...
```

which obviously is not sorted. Am I understanding the issue correctly?
