### ISSUE TITLE
When LDAP is configured, then normal email logins can be blocked if LDAP server is slow/down

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22459]
**Describe the bug**
When LDAP is configured, then normal email users (example the initially created admin user) also causes lookup on LDAP on every login, which is generally slower and unwanted, but if the LDAP server is slow/down, then it's very difficult to login.

**Workaround** Start Metabase with LDAP disabled via the environment variable `MB_LDAP_ENABLED=false`
https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_ldap_enabled
Or alternatively, use the environment variables to change the LDAP server host if needed.

**To Reproduce**
1. Admin > Settings > Authentication > LDAP - setup, so it works.
2. Look at the LDAP debug log, when trying to login with the initial Metabase admin user, which is `core_user.ldap_auth=false`.
It will show lookups in the LDAP log.
```
6273e7ee conn=1009 fd=18 ACCEPT from IP=172.17.0.1:59102 (IP=0.0.0.0:389)
6273e7ee conn=1009 op=0 BIND dn="cn=Manager,dc=metabase,dc=local" method=128
6273e7ee conn=1009 op=0 BIND dn="cn=Manager,dc=metabase,dc=local" mech=SIMPLE ssf=0
6273e7ee conn=1009 op=0 RESULT tag=97 err=0 text=
6273e7f8 conn=1009 op=1 SRCH base="ou=people,dc=metabase,dc=local" scope=2 deref=0 filter="(&(mail=test@test.test))"
6273e7f8 conn=1009 op=1 SRCH attr=*
6273e7f8 conn=1009 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
6273e802 conn=1009 op=2 UNBIND
6273e802 conn=1009 fd=18 closed
```
3. Simulating a terrible connection or the LDAP server might have moved - example:
`tc qdisc add dev docker0 root netem delay 65s`
4. Trying to login now will just result in timeout.

**Expected behavior**
- Email+password users should always be allowed to login.
- There's no reason to do a lookup on LDAP for email users (`core_user.ldap_auth=false`).
**Note** Will this impact existing setups, which have created users on Metabase, and then kinda don't know where the authentication is happening? Until there's a way to configure password logins enabled/disabled, then it might be difficult to know #11322

**Information about your Metabase Installation:**
Tested 0.42.4 and 0.43.0

**Comment by noahmoss** [comment]
The root cause is simply that we try LDAP first if enabled, and fallback to email & password if that fails: https://github.com/metabase/metabase/blob/e864b1f3fb30d916ee5f3d7ef43e76e5de316a62/src/metabase/api/session.clj#L142-L143

We could fix this issue by just swapping the order of lookups, but I think that might also lead to unintended behavior. If a user was created with email & password, but their email also exists in the LDAP server, I think we should preferentially use LDAP to log in so that we ensure that we sync groups and/or attributes if necessary.

So maybe the best fix is just to ensure that we observe a reasonable timeout for LDAP lookups.

**Comment by flamber** [comment]
@noahmoss While I kinda agree, but if the user is without SSO (ldap_auth, sso_login, google_auth = `false`), then the Metabase email+password credentials should always be used. But we've but ourselves in a bind and I don't see a perfect solution until we support #11322

**Comment by iethree** [comment]
This still reproduces. We wait for the ldap server to respond no matter who is logging in, whether or not they were provisioned through ldap. If the server fails quickly, the login is quick, but if the success or failure has a lot of latency, it takes a lot of time, no matter the user.  Here's a docker-compose file you can use to reproduce this locally, by setting up your ldap server to point to localhost:3389

```
version: '3.8'

services:
  # OpenLDAP server
  ldap:
    image: bitnamilegacy/openldap:2.6.4
    environment:
      LDAP_ADMIN_PASSWORD: adminpass
      LDAP_USERS: user01@example.org,user02@example.org
      LDAP_PASSWORDS: 123456,123465
      LDAP_ROOT: dc=example,dc=org
      LDAP_PORT_NUMBER: 389
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - ldap-net

  # Network delay simulator using tc (traffic control)
  delay-proxy:
    image: alpine:latest
    container_name: ldap-delay-proxy
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "
        apk add --no-cache socat iproute2 &&
        tc qdisc add dev eth0 root netem delay 2000ms 500ms &&
        socat TCP-LISTEN:389,fork,reuseaddr TCP:ldap:389
      "
    ports:
      - "3389:389"
    depends_on:
      - ldap
    networks:
      - ldap-net

volumes:
  ldap-data:
  ldap-config:

networks:
  ldap-net:
    driver: bridge
```
