### ISSUE TITLE
Load postgres inside metabase without initial setup via browser

### ISSUE THREAD

**Issue by abhijithneilabraham** [metabase/metabase#23324]
Hi!

Given below is the docker compose file I am using which contains postges and metabase under services:

```
version: '3.7'
services:
  postgres:
    image: postgres:12
    ports:
    - 5432:5432
    restart: 'no'
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: 'no'
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /tmp/hasura_migrations_dir
      HASURA_GRAPHQL_METADATA_DIR: /tmp/hasura_metadata_dir
      ## uncomment next line to set an admin secret

  metabase-app:
    image: metabase/metabase
    restart: 'no'
    ports:
      - 3000:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_CONNECTION_URI: "postgresql://postgres:postgres@IP_ADDRESS:5432/postgres"

    depends_on:
      - postgres
    links:
      - postgres
volumes:
  db_data:
```

The docker compose is run in a remote machine, and the IP_ADDRESS variable in MB_DB_CONNECTION_URI specifies that. When metabase starts up in browser, I want it to start by automatically connecting to the postgres database mentioned, without actually having to going through the procedure of giving db_credentials in the browser console. I thought specifying MB_DB_CONNECTION_URI would help me connect to the db, but it does not. What is the best way to do this?
