### ISSUE TITLE
Connect to MongoDB error: Connection to ... successful, but could not connect to DB.

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#2722]
Hi!
I'm trying to add remote MongoDB 3.2.6 (**auth by login and password**) to Metabase 0.17.1.
Metabase is running from the JAR on Ubuntu 14.04. Java version:

```
$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

Connect from `mongo` client **by login and password** works successfully but when I try to add MongoDB in Metabase Admin Panel I get the error `Connection to ... successful, but could not connect to DB.` and trace below:

```
06-09 12:09:52 DEBUG mongo.util :: << OPENED NEW MONGODB CONNECTION >>
06-09 12:09:55 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=...here my ip...:26017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]
06-09 12:09:55 DEBUG mongo.util :: << OPENED NEW MONGODB CONNECTION >>
```

How to fix the problem?

**Comment by anki-code** [comment]
I've got the same error on java 1.8
```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by anki-code** [comment]
I've built JAR from `master` (ver 0.18) sources and get the same error:
```
06-09 20:03:12 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=...:26017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]

06-09 20:03:12 DEBUG metabase.middleware :: POST /api/setup/validate 400 (3 s)
{:message
 "com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=...:26017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]"}
```

**Comment by anki-code** [comment]
Any thoughts?

**Comment by camsaul** [comment]
Hi @anki-code, sorry for the long delay before replying. Not sure why you're seeing that issue. You're able to connect with the same details using the `mongo` command line client, right?

Can you try connecting to any other Mongo servers if possible?

**Comment by camsaul** [comment]
@anki-code, can you connect to the database from the mongo command line client?

**Comment by camsaul** [comment]
@anki-code?

**Comment by anki-code** [comment]
I've tried to use metabase-0.20 but still have the error:

`Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mymongoserver:28017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]`

@camsaul 
> You're able to connect with the same details using the mongo command line client, right?

Yes.

> Can you try connecting to any other Mongo servers if possible?

I've tried local mongo server on the same host with Metabase. It works.

**Comment by anki-code** [comment]
@camsaul, here is mongo config:

```
security:
 authorization: enabled
 keyFile: /mnt/data/mdb.keyfile
 clusterAuthMode: keyFile

net:
 bindIp: 0.0.0.0
 maxIncomingConnections: 1000000
 port: 28017
 http:
   enabled: false

storage:
 directoryPerDB: true
 dbPath: /mnt/data/db
 journal:
   enabled: true
 engine: wiredTiger

systemLog:
 destination: file
 logAppend: true
 path: /var/log/mongodb/mongod.log
 logRotate: reopen
processManagement:
 fork:  false

replication:
 replSetName: p-prod
 secondaryIndexPrefetch: all
 oplogSizeMB: 2048
```
