### ISSUE TITLE
Investigate and solidify differences between `metabase_database` fields `options` and `settings`

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#30468]
```sql
select id, engine, options, settings from metabase_database where id = 3;
 id |  engine  |             options             |             settings
----+----------+---------------------------------+----------------------------------
  3 | postgres | {"persist-models-enabled":true} | {"database-enable-actions":true}
(1 row)
```

We seem to have two json grab bags in our database table: options and settings. Let's figure out what is going on and make sure everything is where it should be.

```yaml
  - changeSet:
      id: 73
      author: camsaul
      comment: 'Added 0.29.0'
      changes:
        # add a new 'options' (serialized JSON) column to Database to store things like whether we should default to
        # making string searches case-insensitive
        - addColumn:
            tableName: metabase_database
            columns:
              - column:
                  name: options
                  type: text
                  remarks: 'Serialized JSON containing various options like QB behavior.'
```

vs

```yaml
  - changeSet:
      id: v42.00-070
      author: camsaul
      comment: >-
        Added 0.42.0 - add Database.settings column to implement Database-local Settings
      # This migration was originally misnumbered, so now that it has a correct number it may get triggered a second
      # time. That's fine
      preConditions:
        - onFail: MARK_RAN
        - not:
            - columnExists:
                tableName: metabase_database
                columnName: settings
      changes:
        - addColumn:
            tableName: metabase_database
            columns:
              - column:
                  name: settings
                  type: ${text.type}
                  remarks: "Serialized JSON containing Database-local Settings for this Database"
```

Are we doing the correct thing with actions and persistence?
