### ISSUE TITLE
config.yml fails if password contains special characters

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#30916]
### Describe the bug

Trying to initialize Metabase with the following config file:

```
version: 1
config:
  users:
    - first_name: Luiz
      last_name: Arakaki
      password: MetaPa$$123{{>
      email: admin@metabase.com
```

It fails with `clojure.lang.ExceptionInfo: Invalid query: found [[ or {{ with no matching ]] or }} {:type :invalid-query}`

### To Reproduce

Use the config file above

### Expected behavior

It should start Metabase and the admin must use that password

### Information about your Metabase installation

```JSON
46.3
```

### Severity

P2
