### ISSUE TITLE
Fail to start instance with `config.yml` if password contains special characters `{{` or `[[` 

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#31562]
### Describe the bug

When starting an instance with a config file, it fails if the password contains special characters.

### To Reproduce

Create a config.yml file

```
version: 1
config:
  users:
    - first_name: Luiz
      last_name: Arakaki
      password: MetaPa$$123{{>
      email: luiz.arakaki@metabase.com
```

Try to start the instance and see error.

### Expected behavior

It should create the password with special characters.

### Logs

```
clojure.lang.ExceptionInfo: Invalid query: found [[ or {{ with no matching ]] or }} {:type :invalid-query}
```

### Severity

P2

**Comment by luizarakaki** [comment]
This is related to our variable interpolation mechanism. Briefly discussed [here](https://metaboat.slack.com/archives/C04DN5VRQM6/p1686679410566269?thread_ts=1686678003.839409&cid=C04DN5VRQM6)

**Comment by darksciencebase** [comment]
@luizarakaki the slack thread suggests this should work if the password is in quotes. is that so? should we just update the docs and close this issue?

**Comment by luizarakaki** [comment]
The user may need to quote some other special characters, but {{ and [[ will always fail (we tested this by that time). Unless we do something else on our side.

**Comment by devurandom** [comment]
This also affects passwords in database configuration, e.g.
```json
{"version":1,"config":{"databases":[{"name":"[REDACTED]","engine":"[REDACTED]","details":{"ssl":true,"host":"[REDACTED]","port":[REDACTED],"user":"[REDACTED]","password":"i[[fi[REDACTED]","dbname":"[REDACTED]"},"uploads_enabled":true,"uploads_schema_name":"[REDACTED]","uploads_table_prefix":"upload_"}]}}
```

Re: https://metaboat.slack.com/archives/C04DN5VRQM6/p1686679618245839?thread_ts=1686678003.839409&cid=C04DN5VRQM6

In this case the string is already quoted (the JSON subset of YAML does not support unquoted strings), so that's not a workaround.

**Comment by camsaul** [comment]
Can you try qutoing that string? 

```yaml
      password: 'MetaPa$$123{{>'

**Comment by devurandom** [comment]
> Can you try quoting that string?
> 
> ```yaml
>       password: 'MetaPa$$123{{>'
> ```

Same result with single quotes as with double quotes.

Both:
```yaml
{"version":1,"config":{"databases":[{"name":"[REDACTED]","engine":"clickhouse","details":{"ssl":true,"host":"[REDACTED]","port":8443,"user":"[REDACTED]","password":'0''ash[[ash',"dbname":"[REDACTED]"},"uploads_enabled":true,"uploads_schema_name":"[REDACTED]","uploads_table_prefix":"upload_"}]}}
```
And:
```yaml
version: 1
config:
  databases:
    - name: "[REDACTED]"
      engine: "clickhouse"
      details:
        ssl: true
        host: "[REDACTED]"
        port: 8443
        user: "[REDACTED]"
        password: '0''ash[[ash'
        dbname: "[REDACTED]"
  uploads_enabled: true
  uploads_schema_name: "[REDACTED]"
  uploads_table_prefix: "upload_"
```
Result in:
```
clojure.lang.ExceptionInfo: Invalid query: found [[ or {{ with no matching ]] or }} {:type :invalid-query}
```
