### ISSUE TITLE
Add remarks to Metabase tables & columns that don't have them

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3389]
This is an opportunity to better-document our code and lower the barrier to entry for potential contributors or new team members.

I've been adding remarks that explain the purpose of new tables and columns lately when I write new migrations:

``` yaml
databaseChangeLog:
  - changeSet:
      changes:
        - createTable:
            tableName: permissions_revision
            remarks: 'This is used to keep track of changes made to permissions via the admin panel, primarily for auditing purposes. Changes are batched, and a new entry is added for every batch.'
```

They're really handy when I'm poking around the DB in pgAdmin:

![screen shot 2016-09-23 at 12 15 33 pm](https://cloud.githubusercontent.com/assets/1455846/18798561/ee67a78e-8187-11e6-9508-cc31908e9055.png)

So I think we should go back at some point and add remarks for things that don't already have them. 

Related: #3089 (use remarks as initial descriptions when syncing a new DB)
