### ISSUE TITLE
Running docker container with multiple networks binds Jetty to wrong ip-address

### ISSUE THREAD

**Issue by freakinruben** [metabase/metabase#3650]
First of all, great job on making metabase so easy to get started with!

I'm trying to run the metabase docker image using 2 networks, one on which postgresql is (called 'services') and one that has runs nginx as a reverse-proxy (called 'nginx-proxy'). The only way I'm able to get this working right now is to hardcode the internal ip-address for `MB_JETTY_HOST` to the ip-address of the `nginx-proxy` network because otherwise it's listening to the `services` ip-address. This is not a very convenient solution because the ip-address can change every time docker restarts..

The `services` network gives out ip-addresses in the range of `172.20.0.x` and the nginx-proxy network in `172.19.0.x`. When I inspect my metabase-container it has 2 ip-addresses: `172.19.0.3` and `172.20.0.3`.
If I don't specify `MB_JETTY_HOST`, I can curl to `http://172.20.0.3:3000` and get a correct response, but `curl http://172.19.0.3:3000` will give me `curl: (7) Failed to connect to 172.19.0.3 port 3000: Connection refused`

Is there a way to not hard-code the ip-address and for example listen on both networks?

I'm using metabase 0.20.1, docker 1.10.3 on GCE. Here's how my docker-compose looks like:

```
version: '2'

services:
  metabase-dev:
    image: metabase/metabase:v0.20.1
    container_name: metabase-dev
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=xxxxx
      - "MB_DB_PASS=xxxxxx"
      - MB_DB_HOST=postgres
      - "MB_JETTY_HOST=172.19.0.3"
    external_links:
      - postgres
    networks:
      - services-tier
      - proxy-tier

networks:
  services-tier:
    external:
      name: services
  proxy-tier:
    external:
      name: nginx-proxy
```

Update: Using `0.0.0.0` for `MB_JETTY_HOST` seems to work but I'm not sure if it will keep working with future reboots..
