### ISSUE TITLE
Cannot duplicate or save questions when moving from 42 to 49

### ISSUE THREAD

**Issue by satodu** [metabase/metabase#40600]
**Describe the bug**
Cannot duplicate a question

**Logs**
Error 400 card API : should be a boolean, recebido: 0

PUT /api/card/310 400 1.9 ms (0 chamadas ao banco de dados) 
{:errors {:collection_preview "nullable boolean"},
 :specific-errors {:collection_preview ["should be a boolean, recebido: 1"]}}

**To Reproduce**
1. Go to Question
2. Click on Duplicate
3. Click in Duplicate

**Expected behavior**
Duplicate

**Screenshots**
![image](https://github.com/metabase/metabase/assets/3492068/698b2410-8069-4102-8702-f6774ffacef1)

**Severity**
It's very Hard because I copy many 

**Additional context**
It happens if I change something and try to save as another question too.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.4.0-1111-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.32"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by satodu** [comment]
I did changing in the payload from 0 to false, but I don't know where change in the code

**Comment by paoliniluis** [comment]
I just tested this and can't reproduce, are you running Metabase behind a WAF and you're getting the assets of the frontend cached?

**Comment by satodu** [comment]
https://github.com/metabase/metabase/assets/3492068/eff877e1-3865-4aee-82c8-ac446c868afb

No, I am running using kubernetes, with container.

I solved using directly the entrypoint I will try to fix in the code, but I neves used the metabase on local for development, look how I did to solved and above you can see the error.


https://github.com/metabase/metabase/assets/3492068/7b146646-87c1-495e-8f04-f8f209a362f9

**Comment by satodu** [comment]
@paoliniluis please reopen my thread I will try to solve but maybe can help someone.

**Comment by alquerci** [comment]
Hello there,

This issue was caught after migration from version between 0.40 and 0.48 to version 0.49.1.
But no issue from fresh installation of version 0.49.1.

Browser: Firefox 124.0

The request payload
![image](https://github.com/metabase/metabase/assets/2987860/a7c0a1ec-ad58-41a1-b289-81ae7a0c3478)

**Comment by paoliniluis** [comment]
Hi, we need a way to reproduce this, otherwise we can’t fix

**Comment by alquerci** [comment]
@paoliniluis indeed

### In short
Given v0.42.6
When migrate to v0.49.2 and edit and save an existing question.
Then `collection_preview: 1` instead of `collection_preview: true`

### More details steps
1. Start `metabase/metabase:v0.42.6`
2. Create SQL question "What is the version of mysql server?" with `select version()`
3. Stop
4. Start `metabase/metabase:v0.49.2`
5. Open question, "What is the version of mysql server?"
6. Change the SQL content, adding a space is enough
7. Save the question

Using this docker-compose configuration.

```yaml
version: '3.8'

volumes:
  source-database: ~
  metabase-mariadb: ~

services:
  metabase:
    # image: metabase/metabase:v0.49.2
    image: metabase/metabase:v0.42.6
    environment:
      MB_JETTY_HOST: 0.0.0.0
      MB_JETTY_PORT: 3000
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: name
      MB_DB_USER: user
      MB_DB_PASS: pass
      MB_DB_HOST: metabase-mariadb
    depends_on:
      - metabase-mariadb
      - database

  metabase-mariadb:
    image: mariadb:10.11.7
    volumes:
      - metabase-mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: name
      MARIADB_USER: user
      MARIADB_PASSWORD: pass

  database:
    image: mysql:5.7.42-debian
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - source-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
```

**Comment by paoliniluis** [comment]
Interesting, I can't still recognize if this should be tackled by backend or frontend, but clearly we had stuff in 42 that don't work anymore in 49

either way, the repro stack is easier:
```
services:
  metabase:
    image: metabase/metabase:v0.49.2
    # image: metabase/metabase:v0.42.6
    ports:
      - 3000:3000
    environment:
      MB_JETTY_HOST: 0.0.0.0
      MB_JETTY_PORT: 3000
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: name
      MB_DB_USER: user
      MB_DB_PASS: pass
      MB_DB_HOST: metabase-mariadb
    depends_on:
      - metabase-mariadb

  metabase-mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: name
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
```

1) Start v42, initialize it, create a question on the sample db with "select 1", save it
2) stop the stack (do not remove the containers, just stop those)
3) change the line from 42 to 49
4) start the stack again (metabase will perform the migrations
5) open the saved question and add a space or a new line, try to save
you'll get
```
metabase-1          | 2024-04-02 08:14:34,966 DEBUG middleware.log :: PUT /api/card/1 400 5.2 ms (0 DB calls) 
metabase-1          | {:errors {:collection_preview "nullable boolean"},
metabase-1          |  :specific-errors {:collection_preview ["should be a boolean, received: 1"]}}
metabase-1          | 

```

**Comment by paoliniluis** [comment]
Interesting, I can't still recognize if this should be tackled by backend or frontend, but clearly we had stuff in 42 that don't work anymore in 49

either way, the repro stack is easier:
```
services:
  metabase:
    image: metabase/metabase:v0.49.2
    # image: metabase/metabase:v0.42.6
    ports:
      - 3000:3000
    environment:
      MB_JETTY_HOST: 0.0.0.0
      MB_JETTY_PORT: 3000
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: name
      MB_DB_USER: user
      MB_DB_PASS: pass
      MB_DB_HOST: metabase-mariadb
    depends_on:
      - metabase-mariadb

  metabase-mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: name
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
```

1) Start v42, initialize it, create a question on the sample db with "select 1", save it
2) stop the stack (do not remove the containers, just stop those)
3) change the line from 42 to 49
4) start the stack again (metabase will perform the migrations
5) open the saved question and add a space or a new line, try to save
you'll get
```
metabase-1          | 2024-04-02 08:14:34,966 DEBUG middleware.log :: PUT /api/card/1 400 5.2 ms (0 DB calls) 
metabase-1          | {:errors {:collection_preview "nullable boolean"},
metabase-1          |  :specific-errors {:collection_preview ["should be a boolean, received: 1"]}}
metabase-1          | 

```
