### ISSUE TITLE
Docker container startup fail 

### ISSUE THREAD

**Issue by Arjxm** [metabase/metabase#43488]
### Describe the bug

2024-06-03 08:25:08,976 INFO metabase.plugins :: Loading plugins in /plugins...
2024-06-03 13:55:09 2024-06-03 08:25:09,101 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,171 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,180 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,476 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,491 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,492 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,502 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /plugins/athena.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,564 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,569 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /plugins/presto-jdbc.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,614 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /plugins/bigquery-cloud-sdk.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,741 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,744 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2024-06-03 13:55:09 2024-06-03 08:25:09,745 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2024-06-03 13:55:09 #
2024-06-03 13:55:09 # A fatal error has been detected by the Java Runtime Environment:
2024-06-03 13:55:09 #
2024-06-03 13:55:09 #  SIGSEGV (0xb) at pc=0x00007ffffec1b072, pid=1, tid=24
2024-06-03 13:55:09 #
2024-06-03 13:55:09 # JRE version: OpenJDK Runtime Environment Temurin-11.0.23+9 (11.0.23+9) (build 11.0.23+9)
2024-06-03 13:55:09 # Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (11.0.23+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
2024-06-03 13:55:09 # Problematic frame:
2024-06-03 13:55:09 # V  [libjvm.so+0x7ce072]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x42
2024-06-03 13:55:09 #
2024-06-03 13:55:09 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2024-06-03 13:55:09 #
2024-06-03 13:55:09 # An error report file with more information is saved as:
2024-06-03 13:55:09 # /tmp/hs_err_pid1.log
2024-06-03 13:55:09 #
2024-06-03 13:55:09 # If you would like to submit a bug report, please visit:
2024-06-03 13:55:09 #   https://github.com/adoptium/adoptium-support/issues
2024-06-03 13:55:09 #

### To Reproduce

```
version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
```
```docker compose up```

### Expected behavior

On localhost:3000 general Metabsee UI should be visbile 

### Information about your Metabase installation

```JSON
version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
```
```


### Severity

Blocker for docker image user

### Additional context

_No response_
