### ISSUE TITLE
Styles from EmbedFrame are leaking into the global scope in embedding sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#44802]
CSS styles from the EmbedFrame class is leaking into the global `<body>` scope of the user's page, under the React Embedding SDK. This overwrites any background-color the user has set on their body.

See `EmbedFrame.module.css`, first line:

```css
body {
  background-color: transparent;
}
```
