### ISSUE TITLE
java.util.IllegalFormatConversionException Issue on Metabase v0.50.9 

### ISSUE THREAD

**Issue by andidotsugandi** [metabase/metabase#45124]
Hi all,

I am using [Docker Compose file](https://paste.opensuse.org/pastes/f4e10a3fe9ee) to deploy Metabase v0.50.9 (with Postgres 16.3)  on Swarm Cluster:

```
version: '3.9'

services:
  postgres:
    image: postgres:16.3
    volumes:
      - /mnt/nfs/metabase.yoursite.com/postgres-data:/var/lib/postgresql/data
    networks:
      - metabasenetwork
    deploy:
      placement:
        constraints:
          - node.hostname == vm-manager01
      labels:
        - traefik.enable=false
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user_metabase
      POSTGRES_DB_FILE: /run/secrets/postgres_db_metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_user_password_metabase
    secrets:
       - postgres_user_metabase
       - postgres_db_metabase
       - postgres_user_password_metabase

  metabase:
    depends_on:
      - postgres
    image: metabase/metabase:v0.50.9
    volumes:
      - /dev/urandom:/dev/random:ro
      - /mnt/nfs/metabase.yoursite.com/metabase-data:/metabase-data
      - /mnt/nfs/metabase.yoursite.com/metabase-plugins:/plugins
    networks:
      metabasenetwork:
        aliases:
          - metabase.yoursite.com
      proxy:
        aliases:
          - metabase.yoursite.com
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == vm-manager01]
      restart_policy:
        condition: any
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.metabase-secure.entrypoints=websecure"
          - "traefik.http.routers.metabase.entrypoints=web"
          - "traefik.http.routers.metabase-secure.rule=Host(`metabase.yoursite.com`)"
          - "traefik.http.routers.metabase.rule=Host(`metabase.yoursite.com`)"
          - "traefik.http.routers.metabase-secure.service=metabase-service"
          - "traefik.http.routers.metabase-secure.tls.certResolver=letsencrypt"
          - "traefik.http.services.metabase-service.loadbalancer.server.port=3000"
    healthcheck:
      test: curl --fail -I http://metabase:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME_FILE: /run/secrets/postgres_db_metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/postgres_user_metabase
      MB_DB_PASS_FILE: /run/secrets/postgres_user_password_metabase
      MB_DB_HOST: postgres
      JAVA_TIMEZONE: Asia/Jakarta
    secrets:
       - postgres_user_metabase
       - postgres_db_metabase
       - postgres_user_password_metabase
    extra_hosts:
       - "host.docker.internal:host-gateway"

secrets:
   postgres_user_metabase:
     external: true
   postgres_db_metabase:
     external: true
   postgres_user_password_metabase:
     external: true

networks:
  metabasenetwork:
  proxy:
    external: true
```

The log so far is:

```
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Warning: environ value jdk-11.0.23+9 for key :java-version has been overwritten with 11.0.23
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:53:40,703 INFO metabase.util :: Maximum memory available to JVM: 11.8 GB
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:53:49,738 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:08,842 INFO driver.impl :: Registered abstract driver :sql  🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:08,890 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:08,921 INFO metabase.util :: Load driver :sql-jdbc took 493.1 ms
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:08,925 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:09,759 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:09,899 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,525 INFO metabase.core :: 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Metabase v0.50.9 (720e549) 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Copyright © 2024 Metabase, Inc. 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Metabase Enterprise Edition extensions are NOT PRESENT.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,544 INFO metabase.core :: Starting Metabase in STANDALONE mode
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,637 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  {:port 3000, :host "0.0.0.0"}
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,733 INFO metabase.core :: Starting Metabase version v0.50.9 (720e549) ...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,744 INFO metabase.core :: System info:
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  {"file.encoding" "UTF-8",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.runtime.name" "OpenJDK Runtime Environment",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.runtime.version" "11.0.23+9",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.vendor" "Eclipse Adoptium",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.vendor.url" "https://adoptium.net/",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.version" "11.0.23",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.vm.name" "OpenJDK 64-Bit Server VM",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "java.vm.version" "11.0.23+9",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "os.name" "Linux",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "os.version" "5.15.0-113-generic",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "user.language" "en",
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |  "user.timezone" "Asia/Jakarta"}
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:16,748 INFO metabase.plugins :: Loading plugins in /plugins...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,105 INFO plugins.classloader :: Added URL file:/plugins/ojdbc8.jar to classpath
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,107 INFO plugins.classloader :: Added URL file:/plugins/vertica-jdbc-8.0.1-0.jar to classpath
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,222 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,224 INFO driver.impl :: Registered driver :druid  🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,273 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,274 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,484 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? true
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,485 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :vertica...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,486 INFO driver.impl :: Registered driver :vertica (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,523 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid-jdbc...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,524 INFO driver.impl :: Registered driver :druid-jdbc (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,552 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,553 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,554 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,555 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,606 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,607 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,716 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,718 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,728 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,729 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,752 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,753 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,754 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,781 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,782 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,791 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,792 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,822 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,826 INFO driver.impl :: Registered driver :mongo  🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,840 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,842 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,903 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:18,910 INFO db.setup :: Verifying postgres Database Connection ...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:19,983 INFO db.setup :: Successfully verified PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) application database connection. ✅
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:19,984 INFO db.setup :: Checking if a database downgrade is required...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:22,271 INFO db.setup :: Running Database Migrations...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:22,273 INFO db.setup :: Setting up Liquibase...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:22,970 INFO db.liquibase :: Updating liquibase table to reflect consolidated changeset filenames
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:23,007 INFO db.liquibase :: No migration lock found.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:23,008 INFO db.liquibase :: Migration lock acquired.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:23,039 INFO db.setup :: Liquibase is ready.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:23,040 INFO db.liquibase :: Checking if Database has unrun migrations...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:24,837 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:24,854 INFO db.liquibase :: No migration lock found.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:24,854 INFO db.liquibase :: Migration lock acquired.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:25,524 INFO db.liquibase :: Running 336 migrations ...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,771 INFO impl.StdSchedulerFactory :: Using default implementation for ThreadExecutor
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,803 INFO core.SchedulerSignalerImpl :: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,803 INFO core.QuartzScheduler :: Quartz Scheduler v.2.3.2 created.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,806 INFO jdbcjobstore.JobStoreTX :: Using db table-based data access locking (synchronization).
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,810 INFO jdbcjobstore.JobStoreTX :: JobStoreTX initialized.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,811 INFO core.QuartzScheduler :: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'MetabaseScheduler' with instanceId '0f50dc1c8c9c1720083271774'
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   NOT STARTED.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   Currently in standby mode.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   Number of jobs executed: 0
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    |   Using job-store 'org.quartz.impl.jdbcjobstore.JobStoreTX' - which supports persistence. and is clustered.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,812 INFO impl.StdSchedulerFactory :: Quartz scheduler 'MetabaseScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,812 INFO impl.StdSchedulerFactory :: Quartz scheduler version: 2.3.2
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,862 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_0f50dc1c8c9c1720083271774 started.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,908 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_0f50dc1c8c9c1720083271774 shutting down.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,909 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_0f50dc1c8c9c1720083271774 paused.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:31,933 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_0f50dc1c8c9c1720083271774 shutdown complete.
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:36,711 INFO db.custom-migrations :: No forward migration for DowngradeDashboardTab
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:39,081 INFO metabase.core :: Metabase Shutting Down ...
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:39,084 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Exception in thread "Thread-9" java.util.IllegalFormatConversionException: f != java.lang.Long
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:39,122 WARN db.liquibase :: (#object[liquibase.Liquibase 0x2b7e6614 liquibase.Liquibase@2b7e6614])
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.util.Formatter$FormatSpecifier.printFloat(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.util.Formatter$FormatSpecifier.print(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.util.Formatter.format(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.util.Formatter.format(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.lang.String.format(Unknown Source)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at clojure.core$format.invokeStatic(core.clj:5770)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at clojure.core$format.doInvoke(core.clj:5764)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at clojure.lang.RestFn.invoke(RestFn.java:423)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db.liquibase$wait_for_all_locks.invokeStatic(liquibase.clj:258)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db.liquibase$wait_for_all_locks.invoke(liquibase.clj:251)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db.setup$release_migration_locks_BANG_.invokeStatic(setup.clj:175)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db.setup$release_migration_locks_BANG_.invoke(setup.clj:170)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db$release_migration_locks_BANG_.invokeStatic(db.clj:91)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.db$release_migration_locks_BANG_.invoke(db.clj:86)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.core$destroy_BANG_.invokeStatic(core.clj:90)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at metabase.core$destroy_BANG_.invoke(core.clj:81)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at clojure.lang.AFn.run(AFn.java:22)
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase-instance_metabase.1.fi0r9lju9jlo@vm    | Warning: environ value jdk-11.0.23+9 for key :java-version has been overwritten with 11.0.23
```

The complete log message is [here](https://paste.opensuse.org/pastes/0b3336f13dbb).

What do you suggest?

**Comment by andidotsugandi** [comment]
Changing with older version like `v0.50.8`, but the issue still persists.

Please help, and suggestions.

Thank you in advance.

**Comment by dpsutton** [comment]
Hi @andidotsugandi 

I think there are two issues.
1. Your metabase instance is shutting down
2. While shutting down, it's hitting an error clearing locks.

I'll tackle them in reverse order

#### 2. while shutting down it's hitting an error clearing locks

I think this is a red herring. It's bad, and it could leave locks in place. But this is happening when already shutting down. So it's not even a symptom of your issue. I've made a separate issue for us to fix this.

#### 1. Your metabase instance is shutting down

Note the order of the logs:

```
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | 2024-07-04 15:54:39,084 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
metabase-instance_metabase.1.18gh6zvf3fe8@vm    | Exception in thread "Thread-9" java.util.IllegalFormatConversionException: f != java.lang.Long
```

We start shutting down and then hit the error. Your instance shuts down. From your logs it starts at `2024-07-04 15:53:40` and then begins shutting down at `2024-07-04 15:54:39` so about 1 minute. My suggestion is to make your health check longer

```
    healthcheck:
      test: curl --fail -I http://metabase:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
```

My suspicion is that you are deciding your instance is unhealthy and tearing it down before it reports it is healthy. Can you try that and let us know?
