### ISSUE TITLE
Feature: Add a quick launch mode for demoing / debugging

### ISSUE THREAD

**Issue by MrChadMWood** [metabase/metabase#46611]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Very often (via Docker), I include Metabase in projects just to quickly and easily interface with some database data. The only downside is needing to signup with a fake account on the self-hosted Metabase instance. 

I usually keep the Metabase database and the project database underneath the same Postgres server, usually the example below. This is convenient, but it has the side effect that clearing the projects database also means you have to sign up for Metabase again.

**Describe the solution you'd like**
Without cannibalizing the existing paid config file feature, I'd like to see something such as a "demo account" that can be activated with an environment variable. Also, if we could set up a single database connection via environment variables, it would be nice. This way, we can prepare a demo completely with docker.

**Describe alternatives you've considered**
It is possible to keep the Metabase's data in a separate RDBMS instance from the project. I prefer to keep these together though. Also, managing them separately would not address this whole feature request; it would only prevent the need to sign-up again.

**How important is this feature to you?**
nice to have

**Additional context**
Example:
```
services:
  storage:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./storage-postgres/data:/var/lib/postgresql/data/
      - ./storage-postgres/sql/MyProjectDatabase.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: metabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d MyProjectDatabase -h 127.0.0.1"]
      interval: 5s
      timeout: 10s
      retries: 5
    profiles:
      - fullstack
      - storage
    metabase:
      image: metabase/metabase:latest
      container_name: metabase
      volumes:
        - /dev/urandom:/dev/random:ro
        - /metabase-data/:/metabase
      ports:
        - 3000:3000
      environment:
        MB_DB_TYPE: postgres
        MB_DB_USER: admin
        MB_DB_PASS: admin
        MB_DB_HOST: storage
        MB_DB_PORT: 5432
        MB_DB_DBNAME: metabase
      depends_on:
        - storage
      profiles:
        - metabase
```
