### ISSUE TITLE
Bigger browsing tiles for long table name

### ISSUE THREAD

**Issue by Timelessprod** [metabase/metabase#46880]
**Is your feature request related to a problem? Please describe.**
When browsing tables in the "Browse" tab of Metabase, we have a grid of 3 column tiles with folders and table names. Currently those tiles are too short for table or folder names longer than 22-26 characters (depending on the characters used since the font is not monospaced) thus cutting some long names if they overflow this limit.
On the other hand on a 16:9 screen with a descent resolution/scaling, those 3 columns look quite thin compared to the width of the screen, letting lot of empty space around those tiles as shown below:

<img width="2560" alt="Screenshot 2024-08-15 at 11 36 37" src="https://github.com/user-attachments/assets/12031ef4-3e8c-411d-9808-e23d8d768be6">

**Describe the solution you'd like**
If we can make some divs and tiles larger, we would keep the 3 column grid design and make enough horizontal space for long table or folder names making things more readable and easy to find for users while keeping the design idea of this page.

Below are the changes I can suggest based on v0.50.20:

```css
/* Page title "Database" & "Learn about our data" */
.emotion-1wuz3h3 {
    max-width: 80rem; 7* Currently 64rem */
    margin: 0px auto;
    width: 100%;
    display: flex;
}

/* Grid container */
.emotion-nb29dk {
    max-width: 80rem;  /* Currently 64rem */
    margin: 0px auto;
    width: 100%;
    display: flex;
    flex-direction: column;
}

/* Grid */
.emotion-gxd7v6 {
    flex-wrap: wrap;
    margin-left: -0.5rem;
    margin-right: -0.5rem;
    width: 100%;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(24rem, 1fr));  /* Currently repeat(auto-fill, minmax(18rem, 1fr)) */
}
```

The responsiveness of those design changes seem to be ok from what I can see in my browser at different window widths:
<img width="2560" alt="Screenshot 2024-08-15 at 11 43 52" src="https://github.com/user-attachments/assets/bc6826a4-a6cb-45dc-b791-9ba51112e632">
<img width="1460" alt="Screenshot 2024-08-15 at 11 44 19" src="https://github.com/user-attachments/assets/f1a9e1b3-3016-4570-a09d-b68a3c372404">
<img width="1052" alt="Screenshot 2024-08-15 at 11 44 37" src="https://github.com/user-attachments/assets/c9125656-2313-40f4-b649-7baea78037f4">

**Describe alternatives you've considered**
For now what I do is using an extension to manually override the CSS style of those divs to make them larger, not ideal solution especially between upgrades if div class names change.

**How important is this feature to you?**
It's a low effort, medium/high win feature in my opinion. Even if some user won't notice it they'll feel it's easier to find the table they want.

**Additional context**
Screenshots are given above to describe the situation
