### ISSUE TITLE
Migration v49.00-015 cannot be run (on mysql) due to Cannot drop index 'idx_api_key_created_by'

### ISSUE THREAD

**Issue by akarikuu** [metabase/metabase#48338]
### Describe the bug

I am using metabase with mysql as 2 docker containers. When updateing from image: metabase/metabase:v0.48.13 to image: metabase/metabase:v0.49.0 i got an error:

```
Cannot drop index 'idx_api_key_created_by': needed in a foreign key constraint [Failed SQL: (1553) ALTER TABLE `metabase`.`api_key` CHANGE `created_by` `creator_id` INT]
```

Same thing if I do a fresh install with image: metabase/metabase:v0.49.0

Not sure if this is related to mysql (image: mariadb:10.5.3 in my case) or a db setting. But this change cannot be applied 

```yaml
  - changeSet:
      id: v49.00-015
      author: johnswanson
      comment: Rename `created_by` to `creator_id`
      rollback: # not necessary, will be removed with the table
      changes:
        - renameColumn:
            tableName: api_key
            columnDataType: integer
            oldColumnName: created_by
            newColumnName: creator_id
´´´

https://github.com/metabase/metabase/blob/e2b74d79f620a01762e9afa81e21dd999a52a4fe/resources/migrations/001_update_migrations.yaml#L4699



How I solved if for now:

I removed the index fk_api_key_created_by_user_id

```sql
ALTER TABLE `api_key`
	DROP FOREIGN KEY `fk_api_key_created_by_user_id`;
```

Than ran the update again and it finished all migrations.
I readded the key with the name fk_api_key_creator_id_user_id

```sql
ALTER TABLE `api_key`
	ADD CONSTRAINT `fk_api_key_creator_id_user_id` FOREIGN KEY (`creator_id`) REFERENCES `core_user` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT;
```

And then "renamed" the idx_api_key_created_by like this. Strangly that index was already on the new field creator_id and not created_by anymore.
```sql
ALTER TABLE `api_key`
	DROP INDEX `idx_api_key_created_by`,
	ADD INDEX `idx_api_key_creator_id` (`creator_id`) USING BTREE;
```

### To Reproduce

1.  Use this docker-compose.yaml

```yaml
services:
  metabase:
    image: metabase/metabase:v0.49.0
    container_name: metabase
    depends_on:
      - metabasedb
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      JAVA_TIMEZONE: "Europe/Berlin"
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: metabase
      MB_DB_PASS: blablabla
      MB_DB_HOST: metabasedb
    volumes:
      - "./services/metabase/data/:/metabase-data"

  metabasedb:
    image: mariadb:10.5.3
    container_name: metabasedb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      TZ: "Europe/Berlin"
      MYSQL_ROOT_PASSWORD: "blablablaroot"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: "metabase"
      MYSQL_PASSWORD: "blablabla"
      MYSQL_DATABASE: "metabase"
    volumes:
      - "./services/metabasedb/conf/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./services/metabasedb/data:/var/lib/mysql"

```

and this my.cnf

```
[client]
default-character-set = utf8mb4

[mysqld]
character-set-server = utf8mb4
collation-server     = utf8mb4_unicode_ci
character_set_server = utf8mb4
collation_server     = utf8mb4_unicode_ci
```

2. run `docker compose up -d`
3.. run `docker compose logs -f` and see the error message. The container keeps restarting and stopping.

### Expected behavior

THe migration should run without an error.

### Information about your Metabase installation

This is the file after the update:

```json
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.4.0-192-generic",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.3-MariaDB-1:10.5.3+maria~focal"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

blocking if you use msyql/mariadb as the application database
