### ISSUE TITLE
CockroachDB

### ISSUE THREAD

**Issue by benkoller** [metabase/metabase#5050]
Hi,

as [CockroachDB](https://www.cockroachlabs.com/blog/cockroachdb-1-0-release/) just reached a state of "production ready" with their 1.0 release it would be great to see them being supported by Metabase. We're already evaluating it for a couple of projects in our backend and it like it so far, but as we're doing most of our analytics via Metabase we'd need support for CockroachDB before making any serious moves.

SQL-wise it shouldn't be a huge hassle AFAICT.

If there is something we / I can help with let me know, happy to do so.

Cheers,
Ben

**Comment by camsaul** [comment]
Hi @benkoller, we're adding support for various DBs based on community demand. Since you're the only person who's asked for this DB thus far, that might be a while 😉 

If you're familiar with Clojure and feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). A few of our drivers (Presto, Vertica and Crate) were contributed by community members. I'm available to help with any questions you might run into.

Anyone else interested in this driver, please add a :+1: reaction to the issue description rather than adding `+1` or 👍  comments. One way we prioritize issues is by the number of 👍  reactions.

**Comment by wkrause13** [comment]
Just some additional information should anyone wish to use metabase with cockroachdb. I am able to execute SQL queries against a cockroachdb instance through metabase. However, metabase is not listing the tables in the UI, so the query builder does not work.

While the query builder is really nice, I'm comfortable writing my own SQL queries. The core dataviz and dashboarding features work with cockroachdb as far as I can tell.

**Comment by mnzt** [comment]
@wkrause13 Awesome. How does it handle Field Filters?

**Comment by wkrause13** [comment]
@mnzt, it doesn't unfortunately. When creating a new question, you need to select "switch to SQL" and then write your own SQL statement that is compatible with CockroachDB. If you do that, then you can save the question, add it to a dashboard, etc...

I could not figure out how metabase is surfacing the list of tables for the query builder. Despite the fact that the "SHOW TABLES;" command works, the list of tables doesn't populate in the query builder, so it must be requesting it by some other means.  Still awesome it works with raw SQL queries though. 

If you really need the query builder, you could export a snapshot of your cockroachdb data and import it into an instance of postgres. You could then try porting over the SQL the query builder generates to apply to your cockroachdb. I'm not doing anything too complex at the moment, so haven't fully explored that path myself.

**Comment by ans-4175** [comment]
Any updates on using cockroachDB on metabase?

**Comment by christianhuening** [comment]
Would be interested as well.

**Comment by darsenault** [comment]
+1 for CockroachDB support. The last couple of releases have greatly improved some of the areas of non-compatibility with PG like some of the catalog tables, etc. I tried Metabase with CRDB last week and got it to connect OK but it could not access tables in CRDB. I will did in and report back on what the logs say.

**Comment by FrancisVarga** [comment]
Is coming along?

**Comment by Dipen-Dedania** [comment]
+1 for CockroachDB support.

**Comment by SinaZK** [comment]
+1 for CockroachDB support.

**Comment by mazameli** [comment]
Please click the 👍 reaction on the initial description of this issue to have your support for this feature recorded. "+1" comments are not taken into account and only create noise for people who are following this issue. Thanks!

**Comment by mazameli** [comment]
CockroachDB ranks only around 19th on our list of [most-requested database drivers](https://github.com/metabase/metabase/issues?q=is%3Aopen+label%3ADatabase%2F+sort%3Areactions-%2B1-desc+label%3A%22Type%3ANew+Feature%22) for Metabase, and it is unlikely we will get to this soon. However, anyone who is interested is welcome to try writing their own driver and including it as a plugin. See this guide for more information: https://github.com/metabase/metabase/wiki/Writing-A-Driver

Please see this [Amazon Athena driver](https://github.com/dacort/metabase-athena-driver) for a great example of a community-developed database driver.

**Comment by paoliniluis** [comment]
Just did some tests with cockroachdb and our sample dataset with the postgres driver. Hit this issue: https://github.com/cockroachdb/cockroach/issues/40195

**Comment by andrewgy8** [comment]
For all those interested, I just was able to connect our CRDB (22.1.6) to metabase. At first we received the error 

> ERROR: unimplemented: multiple active portals not supported Detail: cannot perform operation sql.PrepareStmt while a different portal is open Hint: You have attempted to use a feature that is not yet implemented. See: https://go.crdb.dev/issue-v/40195/v22.1

However, after some trial and error, I realized that if I limited the results `select * from my_table limit 100`, I was able to retrieve results. After I did that query, I am now able to execute all `select * from my_table` without error. 

Not sure what is happening with autocommit and how metabase is handling the connection to CRDB, but that seemed to solve it for us. 

I was told this by CRDB support, even though we have caching on metabase disabled.

> Generally the error occurs when a connection is reused whilst it still has a query/result in progress. Maybe with the cache it doesn’t go back to the database (and so reuse the connection) in every case. A low number of rows may also fit into the cache so there is no paging taking place. Paging through a result will leave the statement open and so leave the connection exposed to an active portal error should metabase try to reuse it for some other purpose.

**Comment by supernomad** [comment]
Hey yall I am trying to take a whack at this, but struggling with getting a base plugin setup that just imports and uses the pg driver under the hood so I can start tinkering with overriding individual methods, while leaving everything else unchanged. I am struggling a bit with what I need in the plugin. Got to the point where its registered and available in the UI, but can't get it to connect.

I was under the assumption that if I used the "concrete" postgres driver as my parent I wouldn't need to override anything to get it to work in a base case. Is this not correct or am I just doing something silly?

For example this driver.clj
```clojure
(ns metabase.driver.crdb
  (:refer-clojure :exclude [second])
  (:require
   [metabase.driver :as driver]))

(driver/register! :crdb, :parent :postgres)

(defmethod driver/display-name :crdb [_]
  "cockroachdb")
```

And this plugin.yaml
```yaml
info:
  name: Metabase CockroachDB driver
  version: 1.0.0-crdb
  description: Allows Metabase to connect to CockroachDB cluster databases.
driver:
  name: crdb
  display-name: CockroachDB
  lazy-load: true
  parent: postgres
  connection-properties:
    - merge:
        - host
        - placeholder: my-crdb-cluster.example.com
    - merge:
        - port
        - default: 25627
    - merge:
        - dbname
        - name: db
          placeholder: birds_of_the_world
    - name: schema-filters
      type: schema-filters
      display-name: schemas
    - user
    - password
    - ssh-tunnel
    - advanced-options-start
    - default-advanced-options
init:
  - step: load-namespace
    namespace: metabase.driver.postgres
  - step: load-namespace
    namespace: metabase.driver.crdb
```
