### ISSUE TITLE
Starting metabase container 1st time with MariaDB backend throws SQL exception and exits, subsequent startups succeed

### ISSUE THREAD

**Issue by mromero-convoso** [metabase/metabase#53719]
### Describe the bug

Given a docker-compose file like the following:
```
services:
  metabase:
    image: metabase/metabase:v0.52.x
    restart: unless-stopped
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_PORT: 3306
      MB_DB_DBNAME: metabase
      MB_DB_USER: <username>
      MB_DB_PASS: <password>
      MB_DB_HOST: <ip address>
```
Then running "docker compose up" - the first attempt at starting the container will fail as it is initializing the database specified in the environment variables in the compose file.  The next time the container starts up, no error is thrown.  See the attached log for full details.  I am using MariaDB 10.6 as my backend DB.

### To Reproduce

Create a docker-compose file like the following:
```
services:
  metabase:
    image: metabase/metabase:v0.52.x
    restart: unless-stopped
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_PORT: 3306
      MB_DB_DBNAME: metabase
      MB_DB_USER: <username>
      MB_DB_PASS: <password>
      MB_DB_HOST: <ip address>
```
Have a MariaDB 10.6 instance configured with an empty 'metabase' database and its connection details reflected in the docker-compose.yml above, and run "docker compose up".  Also important to note that I have tried using various metabase image tags/versions, from 0.53.x down through some in 0.52.x.

### Expected behavior

The service should not fail on the first startup.

### Logs

[dockerCompose.log](https://github.com/user-attachments/files/18790526/dockerCompose.log)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-02-13",
      "tag": "v0.52.11.2",
      "hash": "b4a1cb4"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.6.21-MariaDB-ubu2004-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "5.4.0-1070-kvm",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Uncertain if this can be ignored
