### ISSUE TITLE
[AWS EB Docker] Increase load balancer idle timeout?

### ISSUE THREAD

**Issue by milgner** [metabase/metabase#5661]
When trying to download a particularly large set of data, the response can sometimes take a bit for processing to finish.

The default load balancer idle timeout that's configured by Elastic Beanstalk is 60 seconds but it [is apparently possible](https://forums.aws.amazon.com/thread.jspa?threadID=161310) to override via `.ebextensions`. Do you think it would make sense to do so or should this be considered too much of an edge case?

The snippet from the linked thread:

```
option_settings:
  - namespace: aws:elb:policies
    option_name: ConnectionSettingIdleTimeout
    value: 90
```

The hard question of course is to what value to configure it...
