### ISSUE TITLE
Docker Image  v0.26.2 throws exception

### ISSUE THREAD

**Issue by beevelop** [metabase/metabase#6219]
- Metabase version: `v0.26.2` (`sha256:ea85d9e09ea642983a1bb79e47fd207c659bb8db7aa4b677332970be3b576364`)
- Docker info
```
Server Version: 17.05.0-ce
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 16.04.3 LTS
```
- Launching the container leads to the following exception
```
metabase_1  | Error: Could not find or load main class java.base.java.net=ALL-UNNAMED
metabase_1  | Error: Could not find or load main class java.base.java.net=ALL-UNNAMED
metabase_1  | Error: Could not find or load main class java.base.java.net=ALL-UNNAMED
```
- The very same configuration does work with `v0.26.1`.

---

<details>
  <summary>docker-compose.yml used to initialize Metabase</summary>
  <p>

```yml
version: "3"
services:
  metabase:
    image: metabase/metabase:${METABASE_VERSION}
    environment:
      MB_JETTY_HOST: 0.0.0.0
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${DB_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASS}
      MB_DB_HOST: database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.frontend.rule=Host:${SERVICE_DOMAIN}"
      - "traefik.port=3000"
    networks: [metabase,traefik]
    links: [database]
    depends_on: [database]
    restart: unless-stopped

  database:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks: [metabase]
    volumes: ["./data/postgres/:/var/lib/postgresql/data"]
    restart: unless-stopped

networks:
  metabase:
  traefik:
    external:
      name: traefik_default
```
</p></details>
