### ISSUE TITLE
running via Docker using slack/smtp cause - ERROR: trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by qmnonic** [metabase/metabase#7054]
Running on `metabase/metabase:v0.28.1` on ubuntu, behind `jwilder/nginx-proxy` and `jrcs/letsencrypt-nginx-proxy-companion`
`docker-compose version 1.18.0, build 8dd22a9`

docker-compose config:
```
  metabase:
    image: metabase/metabase:v0.28.1
    container_name: metabase
    environment:
      VIRTUAL_HOST: <nginx-proxy parameter>
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: <nginx-proxy parameters>
      LETSENCRYPT_EMAIL: <nginx-proxy parameters>
      PUBLIC_URL: https://<some.url.here>
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - <some path>/metabase-data:/metabase-data
      - /etc/ssl:/etc/ssl:ro
    links:
      - dbtunnel
    depends_on:
      - dbtunnel
```

When trying to integrate with slack OR setting up an SMTP host (smtp.google.com), I get the following errors:
```
metabase                 | 03-02 02:26:38 ERROR metabase.email :: Error testing SMTP connection
metabase                 | javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
metabase                 |   nested exception is:
metabase                 | 	javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
metabase                 | 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2102)
metabase                 | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:699)
metabase                 | 	at javax.mail.Service.connect(Service.java:366)
metabase                 | 	at metabase.email$run_smtp_test$fn__23186.invoke(email.clj:126)
metabase                 | 	at metabase.email$run_smtp_test.invokeStatic(email.clj:125)
metabase                 | 	at metabase.email$run_smtp_test.invoke(email.clj:109)
metabase                 | 	at metabase.email$guess_smtp_security.invokeStatic(email.clj:143)
metabase                 | 	at metabase.email$guess_smtp_security.invoke(email.clj:136)
metabase                 | 	at metabase.email$test_smtp_connection.invokeStatic(email.clj:164)
metabase                 | 	at metabase.email$test_smtp_connection.invoke(email.clj:150)
metabase                 | 	at metabase.api.email$fn__37555$fn__37557.invoke(email.clj:78)
metabase                 | 	at metabase.api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)
metabase                 | 	at metabase.api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)
metabase                 | 	at metabase.api.email$fn__37555.invokeStatic(email.clj:68)
metabase                 | 	at metabase.api.email$fn__37555.invoke(email.clj:68)
...
```

Googling suggest an openjdk version issue `FROM java:openjdk-8-jre-alpine`.
