### ISSUE TITLE
Can't connect to mongodb host database

### ISSUE THREAD

**Issue by murilo-campaner** [metabase/metabase#8337]
Hello!

I am having the following problem: I am running the metabase on a docker instance in MacOS and my database is on the host (MongoDB).

I am using the following docker-compose.yml configuration:

```
version: '3'

services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - 4000:3000
    networks:
      - metabase
    extra_hosts:
      - "machinehost.local:192.168.0.117"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=test
      - MB_DB_HOST=postgres

  postgres:
    container_name: metabase_db
    image: postgres
    networks:
      - metabase
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_PASSWORD=test

networks:
  metabase:
```

If I run the command: ```docker exec -i -t metabase bash``` and ```ping machinehost.local``` it pings normally.

However, whenever I try to connect to the database using the machinehost.local host the following error occurs:

```
metabase    | 08-15 20:26:06 ERROR metabase.driver :: Failed to connect to database: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
metabase    | 08-15 20:26:06 DEBUG metabase.middleware :: POST /api/setup/validate 400 (3 s) (0 DB calls).
metabase    | {:errors
metabase    |  {:dbname
metabase    |   "com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]"}}
```

Can anybody help me?

Thanks in advance,
