### ISSUE TITLE
Good docker-compose template - help needed for good template - can be added to docs

### ISSUE THREAD

**Issue by steverowland** [metabase/metabase#8401]
Hello!

Got this docker-compose template, based on https://github.com/italia/daf-recipes/blob/master/metabase/docker-compose.yml

A good docker-compose template seems to be missing in the metabase documentation. 

I wondered why it couldn't be in just 1 docker compose file instead of having the postgres in a seperate build? 

When I try this, Metabase says it can't find the user "metabase" during startup. Any idea? 

ERROR metabase.driver :: Failed to connect to database: org.postgresql.util.PSQLException: FATAL: role "metabase" does not exist

------------

version: '3'
services:
  db:
      container_name: db
      image: postgres:9.6
      volumes:
       - "/srv/postgres-data:/var/lib/postgresql/data"
      ports:
        - "5432:5432"
      environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=SUPERSECRET

  metabase:
    container_name: metabase-app
    image: metabase/metabase:latest
    volumes:
        - "/srv/metabase-app:/data"
    links:
        - db
    ports:
        - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=SUPERSECRET
      - MB_DB_HOST=db

**Comment by jornh** [comment]
Hi there,

I just remembered your recent post here and though I'd quickly share a pointer to another `docker-compose` [file](https://dsc.cloud/badr/note-GzzLARseTc.txt) I just saw referenced in https://github.com/metabase/metabase/issues/8312.

After a *very* quick glance it looks like one difference at least is that you do not have any `networks:` definition. If that's the problem or not I'll leave you with (for now at least 😉). Another difference of course is that the other compose file also includes a Nginx reverse proxy, even configured with SSL with cert fetching from Let's Encrypt etc. Nice stuff - but OTOH should be fairly easy to just skip that part if not needed.

HTH & please keep us posted how you fare...

**Comment by steverowland** [comment]
Hi Jorn, that's really helpful example. That one also has the nginx setup too. 

I'll try that and when it works I'll mail it as a suggestion to the metabase people for their documentation. Thanks for the styling tip too:)

**Comment by dijeesh** [comment]
```
version: '3'

services:

  db:
    container_name: db
    image: postgres:9.6
    restart: always  
    volumes:
      - "/data/metabase/pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=SUPERSECRET 
    networks:
      - metabase

  metabase:
    container_name: metabase-app
    image: metabase/metabase:latest
    restart: always 
    volumes:
      - "/data/metabase/metabase-data:/metabase-data"
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=SUPERSECRET
      - MB_DB_HOST=db
    networks:
      - metabase

networks:
  metabase:
    driver: bridge
```
