### ISSUE TITLE
Allow Night/Dark mode setting

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#9203]
OSX Mojave introduces Dark Mode, which can be considered with CSS:

```css
@media (prefers-color-scheme: dark) { 
  color: white; 
  background: black
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment
