### ISSUE TITLE
Proposal: remove table-heuristic correspondence from x-rays

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9564]
As explained in #9546, table is the worng abstraction level for xray definitions. Many xrays are screaming for an overview (and in fact a single dashboard would often suffice if done right), instead we have a bunch of pretty small and barren per-table xrays/dashboards. 

I propose adding a new section `tables` to the heuristic where you'd explicitly define which tables you are interested in (either based on type or name). Flowing from that dimension definitions could only see (and refer to) the tables defined in the heuristic (shortcut if only one table is used, it can be omitted in dimension definitions). In addition cards should optionally specify source table (if not specified it's inferred from dimensions & metrics, but in some cases involving joins that alone might be ambiguous). 

```
tables:
 - Issues:
     entity_type: GenericTable
     named: issues$
 - Labels:
     entity_type: GenericTable
     named: issues_labels
dimensions:
 - CreatedAt:
     field_type: Issues.CreationTimestamp
 - Label:
     field_type: Lables.Text
     named: name
```

This also solves for problem 3) as it opens name as dimension for table binding
